### ISSUE TITLE
Theme css not loading - default is loading instead

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1006]
I've followed the theme instructions to create a theme called _nova_:
_app/assets/stylesheets/pageflow/themes:
nova/variables.scss
nova.scss
default.scss_ 

The default.scss is for added plugins:
- pageflow-linkmap-page (+ pageflow-external-links)
- pageflow-text-page

The css and css.gz files exist after deploy, which includes precompile.
![screen shot 2018-10-09 at 5 47 34 pm](https://user-images.githubusercontent.com/11877425/46701005-5b57c800-cbec-11e8-90c5-d4a96e730453.jpg)

The theme is set to nova for all accounts:
![screen shot 2018-10-09 at 5 44 12 pm](https://user-images.githubusercontent.com/11877425/46701033-762a3c80-cbec-11e8-99f4-228e08e58338.jpg)

However, the site pulls in the default css on preview:
![screen shot 2018-10-09 at 5 56 32 pm](https://user-images.githubusercontent.com/11877425/46701149-c86b5d80-cbec-11e8-812e-3ff9939164dc.jpg)

I've deleted the Rails-generated application.scss.

variables.scss is rather simple:
```
$theme-name: "nova";

// Set font faces
@font-face {
  font-family: Graphik;
  font-weight: normal;
  font-style: normal;
  src: font-url('GraphikCondensed-Medium-Web.woff')  format("woff"),
        font-url('GraphikCondensed-Medium-Web.woff2')  format("woff2");
}

@font-face {
  font-family: Graphik;
  font-weight: bold;
  font-style: normal;
  src: font-url('GraphikCondensed-Bold-Web.woff')  format("woff"),
        font-url('GraphikCondensed-Bold-Web.woff2')  format("woff2");
}

@font-face {
  font-family: Graphik;
  font-weight: normal;
  font-style: italic;
  src: font-url('Graphik-RegularItalic-Web.woff')  format("woff"),
        font-url('Graphik-RegularItalic-Web.woff2')  format("woff2");
}


// $main-color: #e84d2c;
// $main-color-dark: #b14a08;
// $standard-font: "SourceSansPro";

// For a full list of available variables see:
//
//   http://codevise.github.io/pageflow/theme/master/
//

$page-background-color: #005689;
$page-shadow-color: #005689;
$standard-font: "Graphik";
$standard-font-size: 18px;
```

Thanks for your assistance.

**Comment by tf** [comment]
The theme configured in the "Edit account" form is only used for new entries. Maybe the entry you are looking at was created before you changed the default theme in the account? To change the theme of an existing entry, you have to enable the "Editor theme selection" feature flag and go to "Title and Options > Appearance > Theme" inside the editor.

**Comment by tim-wgbh** [comment]
Ah, ok. It now pulls in nova.....css, and it sees the font declarations, but the variables don't seem to be having any effect - the font is still SourceSansPro

**Comment by tf** [comment]
Hard to tell. Are you seeing any mentions of `Graphik` in the generated stylesheet? `$standard-font` should be the right variable to set. Do you import `variables` before `pageflow/themes/default/base`?

**Comment by tim-wgbh** [comment]
It was an order thing. I'm used to the cascade and putting overrides later. Thanks.
