### ISSUE TITLE
/background_jobs gives 404

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1007]
If I do rake routes, I get this entry:

/background_jobs          #<Resque::Server app_file=".../gems/resque-1.27.4/lib/resque/server.rb">

It doesn't work locally or on EC2

**Comment by tf** [comment]
The way [routes are set up by the install generator](https://github.com/codevise/pageflow/blob/183443f14ab716a98c21cb377a5492ecd925da8d/lib/generators/pageflow/routes/routes_generator.rb#L13) (see also the routes file in your app), you need to be signed with th `admin` flag set. Are you?

**Comment by tim-wgbh** [comment]
Yes.
![screen shot 2018-10-10 at 7 03 40 am](https://user-images.githubusercontent.com/11877425/46733670-f5f0ef00-cc5e-11e8-93d9-3201f137904c.jpg)

**Comment by tf** [comment]
Yeah, appears to be an issue with the order in which the install generator inserts those routes. `Pageflow.routes` (which comes first in the default setup) registers a catch all route of the form `/<entry-slug>`. So you will either have to move the `Resque::Server` block before `Pageflow.routes` or access the Resque web interface via `/background_jobs/overview` which is not matched by the catch all route.

**Comment by tim-wgbh** [comment]
Move the route, thanks.
