### ISSUE TITLE
Videos extend beyond frame

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1010]
Player videos (16x9/1080p) are extending beyond what looks like the expected video area. 

This is exacerbated in full screen mode. It's also causing parts of the captions, which are burned in to be obscured. 

Any ideas about why this might be?

Thanks.
![video-overshoot](https://user-images.githubusercontent.com/11877425/46974578-6a2df700-d092-11e8-928c-50b763aa766b.jpg)

**Comment by tf** [comment]
The video component on the video page uses a sizing strategy that we call "smart contain". It tries to prevent letterboxing/pillarboxing by slightly scaling the video and only falls back to displaying the video in a "contain" style if too much would be cut off. At the moment this behavior is not configurable. We discussed adding an option to the video page to choose between cover (like background video)/smart contain/contain, but there is no concrete plan to work on this change. If you're interested in taking a look, I could provide some pointers. Alternatively, Pageflow also supports the display of vtt/srt based text tracks.

**Comment by tim-wgbh** [comment]
Thanks. Unfortunately, we have captions that are burned in close to the edges, so I've modified the container css to show the entire thing.
