### ISSUE TITLE
Stuck cache?

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1013]
I have placed my two web buckets behind Cloudfront distributions, as well as the PF server.

I have changed the host aliases for the two buckets to custom domains, redeployed/restarted the server, checked the aliases via the console. They are correct. Paperclip assets continue to be requested via the S3 website domain, resulting in a mixed asset warning. I have cleared browser cache,  checked in the database for s3-website configuration.

Is there another cache somewhere that needs to be cleared?

Thank you.

![screen shot 2018-10-16 at 3 21 33 pm](https://user-images.githubusercontent.com/11877425/47041859-e3dbe880-d157-11e8-81b2-3f67d50dde2c.jpg)

**Comment by tf** [comment]
The dynamically generated entry stylesheet where these image urls come from [is cached](https://github.com/codevise/pageflow/blob/master/app/views/pageflow/entries/show.css.erb). So depending on your caching setup you will need to flush the partial cache via `rake tmp:cache:clear` or `Rails.cache.clear`. Alternatively, touching all entries should lead to invalidating the old cache keys.

**Comment by tim-wgbh** [comment]
I did manage to solve this, thanks. However, there seems to be a possibly related issue. I'm seeing blob requests for things that do not exist.  Are these react requests for images (some of them seem to be missing), and as I scroll through the pages, the numbers of them increase. 

Also, although the s3 host alias is defined correctly, the bandwidth probes are being requested directly from the bucket but with https protocol. 

![screen shot 2018-10-18 at 2 35 59 pm](https://user-images.githubusercontent.com/11877425/47176263-28e05600-d2e3-11e8-8566-796c28d9b9af.jpg)

Many thanks for all your help btw.

**Comment by tf** [comment]
The errors regarding the `bandwidth_probe_*` files indicate that you may not have preprocessed assets since you last changed the Paperclip S3 settings. Therefore the asset URLs might not be up to date.

The blob URLs happen on our systems as well. My current hypothesis is that they are somehow caused by `videojs-dash`/MSE. So far I was not able to find a way to prevent those, but also have no indication that they point to any kind of misbehavior.

**Comment by tim-wgbh** [comment]
Hmm. The documentation indicates to put the bandwidth_prove_* files directly in the -out S3 bucket, which would leave them out of the precompile stream. But it doesn't seem to be a problem any  more.

**Comment by tf** [comment]
Yes, but the URLs of the bandwidth probe files are made available to JS via a [`.js.erb` template](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/asset_urls.js.erb#L3), which means things only ever get updates on precompile. Putting these urls into the dynamically generated seed data would have probably been the better choice, but for now that's the way it works :man_shrugging:
