### ISSUE TITLE
Dashboard documentation

### ISSUE THREAD

**Issue by blechdom** [codevise/pageflow#1088]
I am having difficulty finding documentation about how to customize the Dashboard and how install themes for a version of pageflow I am running on a personal server. Can you direct me to any examples or instructions about formatting the Dashboard, or additional information about available themes?
thank you

**Comment by tf** [comment]
Hi,

which dashboard are you referring to exactly? The pages visible at the `/admin` route? Pageflow only comes with a single `default` theme. There are [lots of SCSS variables](http://codevise.github.io/pageflow/theme/master/), though, that can be customized when [creating a custom theme](https://github.com/codevise/pageflow/blob/master/doc/creating_themes.md).

**Comment by blechdom** [comment]
The Admin Dashboard. I am running pageflow locally, and when I go to http://localhost:3000/admin I see the following text: 

> Welcome to Active Admin. This is the default dashboard page.
> To add dashboard sections, checkout 'app/admin/dashboard.rb'

I have looked at the app/admin/dashboard.rb file, and it is not clear how to add all the features seen on the hosted version of pageflow... logo settings, etc... I am also having difficulty finding documentation on customizing the dashboard. I thought it might be included in the "theme," but this is only a guess.

**Comment by tf** [comment]
The dashboard is completely independent of Pageflow. Have a look at the [active admin docs](https://activeadmin.info) for details.

**Comment by tf** [comment]
I'll close this issue now. Feel free to follow up in a new issue or comment here if further questions should come up.
