### ISSUE TITLE
Video play problem in Chrome 71

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#1093]
Hello.

We are seeing a problem with playback of content video (as opposed to background loops) in Chrome 71. It worked in Chrome 70, and also works on latest FF and Safari. Do you have any thoughts on this?

Thank you.

https://stories.wgbh.org/fighting-the-opioid-addiction-crisis-in-buffalo

**Comment by tf** [comment]
From what I see, it looks like you are not using the most recent version Pageflow. [Pageflow 12.4 contains some fixes](https://github.com/codevise/pageflow/blob/12-4-stable/CHANGELOG.md) to be compatible with Chrome's most recent autoplay restrictions.

**Comment by tim-wgbh** [comment]
Great, thank you, did the trick.

Frohe Weinachten
