### ISSUE TITLE
Please be a socially responsible .io domain user

### ISSUE THREAD

**Issue by npscience** [codevise/pageflow#1187]
**Please be a socially responsible .io domain user**
As a prospective user of pageflow (which looks awesome by the way, amazing work!), I care about your logo being on this page: http://www.thedarksideof.io/ <-- read the information linked from this page as to why. My recommendation is for the company to donate (>= cost of web domain renewal) to support the reparation and justice efforts of the displaced Chagossians whose country the .io domain belongs to.
Thank you!

**Comment by tf** [comment]
I've passed this on internally. I'll close this issue now since this issue tracker is meant for code related topics.
