### ISSUE TITLE
Images not processing

### ISSUE THREAD

**Issue by vanlueckn** [codevise/pageflow#1201]
Hello,

i have huge issues with uploading images to my pageflow instance. After starting the upload process i always get the message "Fehler beim Verarbeiten" (processing failed). 

Worker und Scheduler are running without errors. Each uploaded image starts its own processing job (visible at /background-jobs). The process does not show up under failed processes.

I tryed everything listed in Troubleshoot Wiki.
The images do upload to the S3 Bucket. ImageMagick is installed. 

The directory /log/jobs does not exist, so i have no resize log.
All images have a database entry with state = processing_failed.

**Comment by tf** [comment]
The Troubleshooting guide did not reflect the changed log file location that came with the switch to ActiveJob. I updated the page. You need to look at log entries prefixed with `[ActiveJob]` in the normal Rails log.

**Comment by vanlueckn** [comment]
Ok, thank you. It was a problem with ImageMagick (no jpeg and png file extensions supported / listed under convert -list format). After rebuilding ImageMagick with jpeg and png support it now works.
