### ISSUE TITLE
Imprint text not displaying

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#1208]
Hello Pageflow team,

I have an issue with the imprint label not being displayed in my pageflow stories.
The Imprint link label and imprint link URL is set in the account settings but there is nothing displayed. There is a clickable link tag but only the gray background is displayed.

For testing purposes, I added credits to see if those will be displayed. They are not as well. The clickable area is bigger on the gray background but still, nothing displayed.

I hope you can help me with this one. I checked the prod log but the file is clear.

Thanks in advance and best regards,
Ronald

**Comment by tf** [comment]
Could it be [this bug](https://github.com/codevise/pageflow/pull/1185) which was [fixed in 14.2.1](https://github.com/codevise/pageflow/blob/14-2-stable/CHANGELOG.md)?

**Comment by tf** [comment]
Any update?

**Comment by nerdusMaximus** [comment]
Sorry for not responding. This issue was further treated by a coworker of mine. The update you suggested fixed the problem. Thanks for the hint!

Kind regards,
Ronald
