### ISSUE TITLE
failed: resolving dependencies

### ISSUE THREAD

**Issue by i-public** [codevise/pageflow#129]
while "bundle install" after setting up the GEMFILE I get following error:

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    pageflow (>= 0) ruby depends on
      rails (~> 4.0.2) ruby

```
rails (4.1.6)
```

as shown, rails 4.1.6 is installed and shoul meet the needed version > 4.0.2

how to solve this?

Regards, Johannes

**Comment by mab-goe** [comment]
I am experiencing issues with bundler 1.3.0 and current version is 2. plus. can you help?

**Comment by tf** [comment]
Please open a new issue instead of commenting on a closed one, include a link to a gist containing your full `Gemfile` and `Gemfile.lock` and include the exact output/error messages you are seeing.
