### ISSUE TITLE
100% Encoding in progress (Video)

### ISSUE THREAD

**Issue by TobitRE** [codevise/pageflow#1379]
Hi,

i have a problem with the encoding from videos. All works fine, Zencoder geht the job and encode the video. I can found it on AWS and the link in Zencoder is working. But Pageflow show that the video is still encoding.
For Audiofiles and Images it works well.

Some Ideas?

Pageflow 15.1.2

**Comment by tf** [comment]
Hi,

Please check

https://github.com/codevise/pageflow/blob/master/doc/troubleshooting.md

and provide a Gist containing the log entries prefixed with `[ActiveJob]` for the relevant period of time.

**Comment by TobitRE** [comment]
hmmm... sleeping seem to help. Today it works fine. Sorry :/
