### ISSUE TITLE
Video files do not get processed

### ISSUE THREAD

**Issue by sanjuro** [codevise/pageflow#1416]
Hi 

I encounter an issue when trying to upload a new video file, it seems to never get out of the processing state.

I have followed the troubleshooting guide on video file issues

- I have checked my logs on sidekiq and I can see the file is uploaded to zenencoder 
- I see from the logs that the file gets processed by zenencoder and from zenencoders dashboard I can see the request is processed correctly.
- I see that the file is capture with the new url in the DB.

In the pageflow editor, the file just stays in processing state and never completes.

**Comment by tf** [comment]
So files stay pending even if you reload the editor? I'd take a closer look at the logs of the `PollZencoderJob`. Once Zencoder reports success, the job moves on to thumbnail processing. This can fail if, for example, ImageMagick has not been installed. The error then causes files to remain in the processing state.

**Comment by sanjuro** [comment]
Hey Tim, thanks for the response. I checked the install of ImageMagick and it is installed on the system. I had a look at the logs for PollZencoderJob and this is what I see:

[ActiveJob] [Pageflow::SubmitFileToZencoderJob] [9d624b7e-3a9b-42ec-9af2-55e538e46ca4] Enqueued Pageflow::PollZencoderJob (Job ID: e6f9c130-057b-4ebf-b4fc-19542930ea95) to Resque(resizing) with arguments: #<GlobalID:0x0055c5db788c40 @uri=#<URI::GID gid://storytelling/Pageflow::VideoFile/13>>, {}
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95] Performing Pageflow::PollZencoderJob (Job ID: e6f9c130-057b-4ebf-b4fc-19542930ea95) from Resque(resizing) with arguments: #<GlobalID:0x0055c5dc1a8590 @uri=#<URI::GID gid://storytelling/Pageflow::VideoFile/13>>, {}
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95] perform for Pageflow::VideoFile 13
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95]    (0.2ms)  BEGIN
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95]   ↳ /home/ubuntu/pageflow/app/jobs/pageflow/poll_zencoder_job.rb:18
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95]   Pageflow::VideoFile Update (0.4ms)  UPDATE `pageflow_video_files` SET `encoding_progress` = 0.0, `updated_at` = '2020-05-13 08:04:01' WHERE `pageflow_video_files`.`id` = 13
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95]   ↳ /home/ubuntu/pageflow/app/jobs/pageflow/poll_zencoder_job.rb:18
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95]    (1.9ms)  COMMIT
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95]   ↳ /home/ubuntu/pageflow/app/jobs/pageflow/poll_zencoder_job.rb:18
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95] result pending for Pageflow::VideoFile 13
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95] Enqueued Pageflow::PollZencoderJob (Job ID: bb3f7403-75fd-4313-bb0c-bc9964f9749d) to Resque(resizing) at 2020-05-13 08:04:03 UTC with arguments: #<GlobalID:0x0055c5dbea3bb0 @uri=#<URI::GID gid://storytelling/Pageflow::VideoFile/13>>, {}
[ActiveJob] [Pageflow::PollZencoderJob] [e6f9c130-057b-4ebf-b4fc-19542930ea95] Performed Pageflow::PollZencoderJob (Job ID: e6f9c130-057b-4ebf-b4fc-19542930ea95) from Resque(resizing) in 949.47ms

**Comment by tf** [comment]
This looks normal. The job polled Zencoder and updated the video file with a progress of zero percent. Is this the only job of this kind you see? Maybe there is something wrong with the job scheduler? In its default setup Pageflow uses Resque scheduler to perform jobs after a delay. When a video file is pending the job is enqueued to check again after a couple of seconds.

**Comment by sanjuro** [comment]
The PollZencoderJob only everyone runs once and never updates the progress. Im running the default Resque setup with Redis. What job should run after PollZencoderJob?

**Comment by tf** [comment]
Is the [`resque:scheduler` rake task](https://github.com/codevise/pageflow/blob/master/lib/generators/pageflow/procfile/templates/Procfile#L3) running? The PollZencoderJob should enqueue itself to run again after 5 seconds or so if the file is still pending.

**Comment by sanjuro** [comment]
Awesome, that was the issue. I had restarted my server and the resque:scheduler job had not come up again. Thanks for all the help.

**Comment by tf** [comment]
Glad we figured it out! :tada:
