### ISSUE TITLE
Scroll indicator for chapters

### ISSUE THREAD

**Issue by Wiwaltill** [codevise/pageflow#1830]
The menu does not show which chapter you are in. It statically colours the first or the clicked menu item.

**Comment by tf** [comment]
This is now fixed on `master` and will be deployed to Hosted Pageflow later today.

**Comment by tf** [comment]
This is now fixed on `master` and will be deployed to Hosted Pageflow later today.

**Comment by tf** [comment]
Now deployed to Hosted Pageflow.
