### ISSUE TITLE
s3-signature v2 not supported for new region frankfurt on amazon s3

### ISSUE THREAD

**Issue by i-public** [codevise/pageflow#188]
Hello!

I have a problem with zencoder and s3. The video files were successfully uploaded to our s3, but the zencoder job fails with 400 while trying to download.

I talked to the zencoder support and we concluded that everything is ok on side of zencoder, but the transformed link is not working.

I tried this directly and got an error from s3:

< Error>
< Code>InvalidRequest< /Code>
< Message>
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
< /Message>
< RequestId>{xxx}< /RequestId>
< HostId>
{xxx}
< /HostId>
< /Error>

looking for help I stumbled upon this stackoverflow-question: http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

There they say, that the new region frankfurt on s3 will not work on signature version v2, so we have to provide v4 in code.

Amazon help (http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html) says that the ruby config.yml has to be corrected.

Is there a place in pageflow where to do this or should I change ruby directly?

**Comment by davidsoncasey** [comment]
@i-public did you ever resolve this? I'm running into a similar issue trying to use Zencoder with an S3 bucket in the eu-central-1 region. Any tips would be much appreciated.
