### ISSUE TITLE
Minio instead of AWS S3?

### ISSUE THREAD

**Issue by ninoppp** [codevise/pageflow#1954]
[Minio](https://min.io/) is supposed to work seamlessly as an open source S3 replacement - does anyone know if it works with pageflow or is aware of any issues that should be caused?

**Comment by tf** [comment]
Far as I know, this hasn't been tried yet. Looking at https://github.com/minio/minio/issues/3117#issuecomment-256812203, I'd expect it to work, though, when integrated correctly into [Pagefow's Paperclip settings](https://github.com/codevise/pageflow/blob/master/doc/setting_up_external_services.md#configuring-paperclip).

Let us know how it goes!

**Comment by tzortzispanagiotis** [comment]
@ninoppp 
Did you have any success on this? Did you connect Pageflow with your minio instance? I am interested on doing exactly the same
