### ISSUE TITLE
Docker instructions/tutorial

### ISSUE THREAD

**Issue by NickHatBoecker** [codevise/pageflow#2091]
Dear pageflow team,

are there any instructions on how to create a docker container with pageflow?
Our current pageflow version is 15.8.0 and I would like to create a docker for this app, so other team members can easily work on this project. At the moment we cannot test changes locally and have to deploy everything to a test system. 😅 

Thanks in advance!

Best regards
Nick

**Comment by tf** [comment]
Creating such a Docker setup is not really specific to Pageflow, but rather about containerization of Rails applications. There are plenty of resources on the web that showcase different approaches. Giving detailed instructions here is therefore out of scope for Pageflow and goes beyond what we can offer in terms of support for the open source project. Happy to answer specific Pageflow related questions, though, that come up while building such a setup.
