### ISSUE TITLE
External Links disappearing 

### ISSUE THREAD

**Issue by rbrenner-snoop** [codevise/pageflow#2109]
Hello Pageflow Team,

in our new Pageflow 16 Installation our customer found a strange bug.

In the editor of a traditional pageflow page there is a Hotspots page configured. This page did already exist before the upgrade to Pageflow 16.

When i go to the configuration of the single areas there are nearly all Links marked with a red warning sign and their names are all "not named" (or "Unbenannt" in our case).

![error_hotspot_page](https://github.com/codevise/pageflow/assets/67776504/fa61a372-39d3-46a7-8642-dfd84a2f8976)

They are working though. The live page does have links which are working just fine.

If i want to change the links i need to configure new external links in the first Menu where nothing is visible by now.
![external_links_menu_empty](https://github.com/codevise/pageflow/assets/67776504/8372b191-05b9-41bb-8414-13b07b8dd4f6)

If a add a new link i can use it directly afterwards. As soon as i visit the editor for the next time the link is gone again but is fully functioning on the live page if i published it.

One hint for the possible error could be an error i get in the browser console:
`GET https://my.domain.de/external_links/entries/138/sites 404 (Not Found)`

Do you have a hint how i can fix this behaviour?

Thanks and best regards
Ronald

**Comment by tf** [comment]
This could be another case of #1957. Maybe `Pageflow.routes(self)` still comes before `mount Pageflow::ExternalLinks::Engine, at: '/external_links'` in your `config/routes.rb`?

**Comment by rbrenner-snoop** [comment]
Sorry for my late response. This was exactly the issue. Thanks for the hint.
