### ISSUE TITLE
Problem updating to 0.7.0

### ISSUE THREAD

**Issue by thy1985** [codevise/pageflow#250]
Hi,

I started the upgrade on my virtual dev system and while the stories seem to display fine (besides the DOM changes for which I need to update our theme) the admin panel cannot be opened:
![screen](https://cloud.githubusercontent.com/assets/4712663/6026318/28df4f8c-abda-11e4-884d-48ec213f9620.png)

Please be so kind to help me in getting round this. Not sure where I made a mistake. Is there anything more you need to understand the issue?

Thanks a lot in advance!

Cheers,

**Comment by tf** [comment]
Hi,

is it possible that you are using Rails 4.1 and Formtastic 2.3.0.rc2? I had to update Formtastic to 2.3.0. Rails 4.1 appears to have changed some interfaces of form builder methods which older Formtastic version rely on. If that's not it, please provide the full stack trace of the exception.

Cheers

**Comment by thy1985** [comment]
hi tf,

Switched to:
Using rails 4.0.2 (was 4.1.9)
Using formtastic 2.3.0 (was 2.3.0.rc2)

Works now. Thanks for the pointers. BTW, when using older rails but formtastic rc2 it spits out deprectaion warnings. Looks like extra .css in the scss files (active admin) is no longer necessary.

Thanks again!
Cheers,

**Comment by tf** [comment]
I'd recommend sticking with 4.1. Rails 4.0 [no longer receives security fixes](http://rubyonrails.org/security/). So you'll need to update sooner or later anyway. See the Gemfile fragment in the README for a working set of gems for Rails 4.1.

Regarding the deprecation warnings: We'll remove the extra file suffix eventually, but for now it does not hurt far es I can tell.

Cheers

**Comment by thy1985** [comment]
thanks for the hint. Using rails 4.1.9 works fine when the state_machine is added as per the README.
