### ISSUE TITLE
pageflow-chart plugin: wiki page errors

### ISSUE THREAD

**Issue by thy1985** [codevise/pageflow#253]
Just a few remarks to:
https://github.com/codevise/pageflow-chart
a)
gem 'pagflow-chart'
=>
-e missing
b)
Mutiple .scss.css that should be .css.scss
(same for https://github.com/codevise/pageflow-embedded-video)

bundle install missing before install + run migrations

**Comment by tf** [comment]
Please open issues for plugins like `pageflow-chart` in the [issue tracker](https://github.com/codevise/pageflow-chart/issues) of the corresponding repository. Regarding the corrections listed above, I'd be happy to accept a pull request,
