### ISSUE TITLE
Background videos on mobile devices

### ISSUE THREAD

**Issue by shofer** [codevise/pageflow#255]
Is it possible to activate background videos on mobile devices like the iPad?

**Comment by tf** [comment]
As stated in the Mobile Safari Documentation, [autoplay is not supported](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html) on iOS devices (see the warning section half way down the page). Playback can be triggered from user initiated events (click etc.) in certain cases. So there are some more or less hackish [workarounds](http://stackoverflow.com/a/19922031/818309). For phones, which play videos in a separate player overlay, this obviously does not make sense. For tablet support, a couple of questions would have to be answered:

* Is there a workaround that works on tablets across browser and OS versions? If background videos only work on a fraction of tablets, it would still be perceived as a bug.

* Can playback only be triggered from click events? Or is any user even good enough, i.e. could we use a swipe event on page change to trigger a video?

* How do we handle background videos on the first page of an entry? Obviously if there hasn't been any user interaction yet, how can we trigger playback? Should we hijack the click on the button displayed in the multimedia alert overlay?

Most important we would need to find a way to implement this without making a mess.

**Comment by tilsammans** [comment]
#583

**Comment by tf** [comment]
Background videos now can be played without sound on mobile devices.
