### ISSUE TITLE
gem aws-sdk needs to be < 2.0

### ISSUE THREAD

**Issue by grgr** [codevise/pageflow#258]
This might be a minor to resolve error. 
One needs to set ` gem 'aws-sdk' , '< 2.0' ` in the Gemfile to fit dependencies.

**Comment by tf** [comment]
My mistake. I originally released 0.7.1 to fix the `aws-sdk` version. Wanted to introduce pessimistic versions for all gemspec items while I'm at it and managed to skip the `aws-sdk` gem somehow. I'll release 0.7.2 later today. Thanks for the heads up!

**Comment by tf** [comment]
Released 0.7.2
