### ISSUE TITLE
Images not uploading on s3 

### ISSUE THREAD

**Issue by railization** [codevise/pageflow#275]
I have configured pageflow from scratch and accorfing to the documentation. The issue is when I try to upload an image to pageflow , it gives an error which is "Upload failure". When I click on the image and write something in credits textbox it starts processing and gives the message that upload is successful and image turns black.

I have configured the foreman job for resque jobs and they all are working fine alongwith redis server. Can you help me solving this issue. alo the pageflow paperclip and zencoder settings are as under:
config.paperclip_s3_default_options.merge!(
   
    },
    :s3_host_alias => 'com-leon-pageflow-development.s3-website-ap-southeast-1.amazonaws.com',
    :s3_protocol => 'http'
  )
config.zencoder_options.merge!(
 
    :s3_protocol => 'http',
    :attachments_version => 'v1'
  )

I will make a separate file to load the variables but first it needs to upload some images to s3. Please look and help me.

**Comment by tf** [comment]
Hi,

just the "Upload failure" error message alone is too little information to help you. What is the exception you see in the rails log file when you upload an image?

As an aside: I'd advice against publicly posting credentials of paid services like AWS/Zencoder. 

Cheers 
Tim

**Comment by railization** [comment]
Hi Tim,

That was just a blunder however I have deleted that information from the question. I will update you with upload failure error shortly.

Thanks,

Mike

**Comment by railization** [comment]
The server log never stops but i manage to get this chunk 
Started PUT "/entries/1/edit_lock?timestamp=1427480912516" for 127.0.0.1 at 2015-03-27 19:28:32 +0100
19:28:32 web.1    | Processing by Pageflow::EditLocksController#update as JSON
19:28:32 web.1    |   Parameters: {"edit_lock"=>{"id"=>"14"}, "timestamp"=>"1427480912516", "entry_id"=>"1"}
19:28:32 web.1    |   User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1
19:28:32 web.1    |   Pageflow::Entry Load (0.1ms)  SELECT `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`slug` = '1' ORDER BY `pageflow_entries`.`id` ASC LIMIT 1
19:28:32 web.1    |   Pageflow::Entry Load (0.1ms)  SELECT `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`id` = 1 LIMIT 1
19:28:32 web.1    |   Pageflow::Entry Load (0.1ms)  SELECT `pageflow_entries`.* FROM `pageflow_entries` INNER JOIN `pageflow_memberships` ON `pageflow_entries`.`id` = `pageflow_memberships`.`entry_id` WHERE `pageflow_memberships`.`user_id` = 1
19:28:32 web.1    |   Pageflow::EditLock Load (0.3ms)  SELECT `pageflow_edit_locks`.* FROM `pageflow_edit_locks` WHERE `pageflow_edit_locks`.`entry_id` = 1 LIMIT 1
19:28:32 web.1    | Unpermitted parameters: timestamp, entry_id
19:28:32 web.1    |   User Load (0.1ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
19:28:32 web.1    |    (0.1ms)  BEGIN
19:28:32 web.1    |   SQL (0.2ms)  UPDATE `pageflow_edit_locks` SET `pageflow_edit_locks`.`updated_at` = '2015-03-27 18:28:32' WHERE `pageflow_edit_locks`.`id` = 14
19:28:32 web.1    |    (42.5ms)  COMMIT
19:28:32 web.1    | Completed 204 No Content in 51ms (ActiveRecord: 43.6ms)
^CSIGINT received
19:28:33 system   | sending SIGTERM to all processes
19:28:33 worker.1 | terminated by SIGTERM

and also I get these errors in browser console
 POST http://localhost:3000/editor/entries/1/files/image_files 500 (Internal Server Error)
Detail:
sendjquery.js?body=1:9177 jQuery.extend.ajaxjquery.fileupload.js?body=1:712 sendjquery.fileupload.js?body=1:773 $.widget._onSendwidget.js?body=1:116 (anonymous function)jquery.fileupload.js?body=1:812 newData.submituploader_view.js?body=1:25 $el.fileupload.addwidget.js?body=1:515 $.Widget._triggerjquery.fileupload.js?body=1:815 (anonymous function)jquery.js?body=1:384 jQuery.extend.eachjquery.fileupload.js?body=1:805 $.widget._onAddwidget.js?body=1:116 (anonymous function)jquery.fileupload.js?body=1:985 (anonymous function)jquery.js?body=1:3120 firejquery.js?body=1:3166 self.addjquery.js?body=1:3267 promise.alwaysjquery.fileupload.js?body=1:979 $.widget._onChangewidget.js?body=1:116 (anonymous function)widget.js?body=1:426 handlerProxyjquery.js?body=1:4642 jQuery.event.dispatchjquery.js?body=1:4310 elemData.handle

and these two errors
GET http://com-example-pageflow-out.s3-website-eu-west-1.amazonaws.com/bandwidth_probe_small.png?1427481086061 404 (Not Found)
edit:1 GET http://com-example-pageflow-out.s3-website-eu-west-1.amazonaws.com/bandwidth_probe_large.png?1427481086061 404 (Not Found)
high_bandwidth.js?body=1:6 Detected bandwidth 0KB/s. High: No
high_bandwidth.js?body=1:6 Detected bandwidth 0KB/s. High: No
video.js?body=1:1123 ["Video Error", Object]

**Comment by tf** [comment]
The edit lock polling you see in the log is normal behavior. You either need to grep for the 500 response to find the stack trace or simply view the server response in the browser's network console. The two 404 errors occur either because you have not uploaded the bandwidth probe files to your s3 bucket as described in the "setting up external services" wiki page or due to some other s3 configuration error.

**Comment by railization** [comment]
I have uploaded the two images in the bucket. Can you paste me a reference of pageflow.rb file as I think I am erring in setting up the configurations in config/initializers/pageflow.rb.

**Comment by tf** [comment]
The missing image are not related to your problem. Please provide the stack trace of the Internal Server Error you are seeing in the browser console.

**Comment by railization** [comment]
Initially there was the error of not installied imagemagick but after installing it as gem and on ubuntu as well I got this error in the console:
Errno::ECONNREFUSED in Pageflow::Editor::FilesController#create
Connection refused - connect(2) for "com-xxx-xxxxxx-development.s3-website-ap-southeast-1.amazonaws.com" port 443

Pageflow is not connecting to the bucket I think but I have configured the api keys correctly.

**Comment by tf** [comment]
Ah ok, now I think I see your configuration error. Even though the snippet in your first post got mangled up somehow, it looks like you are using an incorrect `s3_host_name`. See the [AWS list of regions and enpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for the correct value. The `s3-website-ap-southeast-1` host can only be used for static file serving (hence it is used correctly for the `s3_host_alias`) not for accessing the REST API.

**Comment by railization** [comment]
I have changed the host name now and that error is not showing up right now,however this error is now coming : 
SocketError in Pageflow::Editor::FilesController#create
getaddrinfo: Name or service not known

**Comment by tf** [comment]
It means the hostname you entered does not exist.

Railization <notifications@github.com> schrieb am Sa., 28. März 2015 20:57:

**Comment by railization** [comment]
Errno::ECONNREFUSED in Pageflow::Editor::FilesController#create
Connection refused - connect(2) for "com-leon-pageflow-development.s3-website.eu-central-1.amazonaws.com" port 443

This is the error now and I have seen the hostname from this document http://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by kioopi** [comment]
Have you seen the docs in the [Wiki](https://github.com/codevise/pageflow/wiki)? 
Especially [Getting Started](https://github.com/codevise/pageflow/wiki/Getting-Started) and [Setting up external services](https://github.com/codevise/pageflow/wiki/Setting-up-External-Services) may be helpful.

**Comment by tf** [comment]
@railization you are stillt using the `s3-website` endpoint, not the API endpoint. I have [updated the wiki page](https://github.com/codevise/pageflow/wiki/Setting-up-External-Services#configuring-paperclip) with more detailed instructions on how to configure paperclip.

**Comment by railization** [comment]
Let me try that Cheers.

**Comment by railization** [comment]
Thanks for your help Tim. It is working now.

**Comment by tf** [comment]
Happy to hear that.

**Comment by tssh-dev** [comment]
Hi I got this error

aws_host_alias is -> http://mybucket.s3-website.us-east-2.amazonaws.com

(52.5ms)  COMMIT
Unpermitted parameters: rights, configuration
Unpermitted parameters: rights, configuration
Unpermitted parameters: configuration, attachment
Unpermitted parameters: rights, configuration, attachment
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/d5f016b090a4e2b6828cc44d0b46a91320171109-8095-1khn4d4.jpeg[0]' 2>/dev/null
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `pageflow_image_files` (`unprocessed_attachment_file_name`, `unprocessed_attachment_content_type`, `unprocessed_attachment_file_size`, `unprocessed_attachment_updated_at`, `width`, `height`, `state`, `entry_id`, `created_at`, `updated_at`) VALUES ('job_post.jpeg', 'image/jpeg', 6053, '2017-11-09 06:46:19', 300, 168, 'not_processed', 3, '2017-11-09 06:46:20', '2017-11-09 06:46:20')
[paperclip] saving user063/image_files/unprocessed_attachments/000/000/004/original/job_post.jpeg

[AWS S3 200 320.419777 10 retries] put_object(:acl=>:public_read,:bucket_name=>"mypageflow",:cache_control=>"public, max-age=31536000",:content_length=>6053,:content_type=>"image/jpeg",:data=>Paperclip::UploadedFileAdapter: job_post.jpeg,:key=>"ptiweb063/image_files/unprocessed_attachments/000/000/004/original/job_post.jpeg") SocketError getaddrinfo: Name or service not known

   (57.9ms)  ROLLBACK
Completed 500 Internal Server Error in 322045ms (ActiveRecord: 113.2ms)

SocketError (getaddrinfo: Name or service not known):

**Comment by danieloi** [comment]
Image could have a bad name (for example, the name could begin with a number)

**Comment by nerdusMaximus** [comment]
@tf do i understand it right that you have to configure CloundFront to deliver images via SSL or what do you mean with the API endpoint in your prior message?

> @railization you are still using the `s3-website` endpoint, not the API endpoint. I have [updated the wiki page](https://github.com/codevise/pageflow/wiki/Setting-up-External-Services#configuring-paperclip) with more detailed instructions on how to configure paperclip.

https://pageflow.daad.de/theme-testing

**Comment by nerdusMaximus** [comment]
> Regarding SSL: S3 used to only support HTTP access, requiring Cloudfront for SSL. They now also support HTTPS URLs of the form `https://s3-eu-west-1.amazonaws.com/your-bucket-name`.

Then i still dont get how to configure this into the paperclip configuration. I looked into https://www.rubydoc.info/gems/paperclip/Paperclip/Storage/S3 but dont rly get how this translates to my pageflow configuration. Is it possible to make pageflow use the HTTPS URLs that you described?

Thanks a lot! If i should open another issue for this than i can do this of course.

**Comment by tf** [comment]
You could use a production config like (assuming that you bucket is in region `eu-west-1`):

```ruby
config.paperclip_s3_default_options.merge!(
    s3_credentials: {
      ...
    },
    s3_host_alias: "s3-eu-west-1.amazonaws.com/your-bucket-name",
    s3_protocol: "https"
  )
```

I haven't worked without a CDN in production. So if loading files directly from S3 should turn out to be too slow, you'll have to switch to Cloudfront or another CDN. Does that answer your question?
