### ISSUE TITLE
Page Typ "background audio"

### ISSUE THREAD

**Issue by gingko24** [codevise/pageflow#277]
Hello,

I couldn`t find the new Page Typ "background audio". Is the new Page Type only available in the hosting version?

Thanks a lot and best regards

gingko24

**Comment by tf** [comment]
Hi,

no, as of `v0.7` it is [part of the gem](https://github.com/codevise/pageflow/blob/v0.7.2/lib/pageflow/built_in_page_type.rb#L51).

Tim

**Comment by tf** [comment]
Sorry, I meant `v0.5`. There is also a [note in the CHANGELOG](https://github.com/codevise/pageflow/blob/master/CHANGELOG.md#manual-update-step-1) how to enable it.

**Comment by gingko24** [comment]
Sorry, I added the recommended line and now the page type works fine.

Thanks.
