### ISSUE TITLE
Error on moving a site inside a chapter

### ISSUE THREAD

**Issue by ablotny** [codevise/pageflow#281]
Hi,

I get the following error on moving a site to another position inside a chapter:

1 Datensätze konnten nicht gespeichert werden. Erneut versuchen

Unfortunately I cannot find any hints in the application log what is causing the error.
I am using gem version 0.5.0 of pageflow.

Do you have any suggestions how to find the cause of the problem?

Kind Regards,
Alex

**Comment by tf** [comment]
Hi,

have you looked in the Network Panel of the Dev Tools in the Browser? Each such error corresponds to a failed request. In the Dev Tools you should be able to see a server response which will help trace the error.

Tim

**Comment by ablotny** [comment]
Good idea but unfortunately it does not reveal much more.

The first request is:
PATCH http://domain.de/chapters/169/pages/order
which gets a 204 No Content as answer

The second one is:
GET http:/domain.de/entries/11/partials
which gets a 500 Internal Server Error

Alex

**Comment by tf** [comment]
Well, if there is no helpful response visible in the client, you'll have to hunt down that 500 in your production.log to find the stack trace.

By the way: The error occurs while reordering pages. Does the new order get saved? So when you reload the editor after the error occured, are the pages in the new or still in the old order?

**Comment by ablotny** [comment]
I found the error. It was caused by a little change in the header.html.erb file. I reverted our change but another problem occurs.

It is a strange behaviour as it works in Firefox but not in Chrome or Safari.
Now the PATCH request has an issue:
http://domain.de/chapters/87/pages/order
results in a 400 Bad Request

In Firefox there is a 204 as answer and everything works fine.

The response looks the following:

ERROR

The requested URL could not be retrieved

While trying to process the request:

PATCH http://reportage-development.welt.de/chapters/87/pages/order HTTP/1.1
Host: reportage-development.welt.de
Proxy-Connection: keep-alive
Content-Length: 37
Origin: http://domain.de
X-CSRF-Token: /s0SuIRwM89/i0AglC0O4LQPjK9s5+IAbua1affgyG0=
X-Edit-Lock: 191
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Content-Type: application/json
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
Referer: http://domain.de/entries/test123/edit
Accept-Encoding: gzip, deflate, sdch
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: ...

{"ids":[270,267,286,285,345,447,462]}
The following error was encountered:

Invalid Request
Some aspect of the HTTP Request is invalid. Possible problems:

Missing or unknown request method
Missing URL
Missing HTTP Identifier (HTTP/1.0)
Request is too large
Content-Length missing for POST or PUT requests
Illegal character in hostname; underscores are not allowed




Did you encounter any issues before with PATCH? Although it is a long time in the HTTP specification it seems not to be used very often.

Thx,
Alex

**Comment by tf** [comment]
Using methods like PATCH and PUT is the default Backbone/Rails approach. Also, we never ran into issues so far. Googling the "Some aspects of HTTP Request is invalid" error message, brings up references to proxy servers like "Squid". Do you happen to use such a setup? The error message must be coming from some part of your stack, that cannot handle the request made inside Chrome.

**Comment by ablotny** [comment]
Okay understood. Thank you very much for your help.
Using HTTPS is also an option, because the Squid does not care about HTTP-communication anymore.

**Comment by tf** [comment]
Just so you know: Backbone does support [HTTP method emulation](http://backbonejs.org/#Sync-emulateHTTP) turning all PATCH/PUT/DELETE requests into POST requests and using Rails magic `_method` request parameter. In the context of Pageflow this is totally untested, though.
