### ISSUE TITLE
pageflow performance

### ISSUE THREAD

**Issue by thy1985** [codevise/pageflow#287]
Hi there

I am aware that there is #18 . But admittedly I do not know much about ruby and thus I can't figure out how I can make sure my installation is using memcache(d) and if not how to improve that - also the link doesn't help me much. I will starting digging deeper into the topic now but if anyone has a more straight forward guide to share I'd really appreciate that.

What I did so far is:
Install and configure memcached (localhost, default port)
add Dalli to bundle + install it
Ensure that I have the following settings in config/environments/production.rb
```
config.cache_classes = true
config.action_controller.perform_caching = true
config.assets.debug = false
config.cache_store = :dalli_store
```
I am not sure what to do here - is it good to be eager (:)):
```
# Do not eager load code on boot.
  config.eager_load = false
```
Are there any low hanging fruits to improve performance (some setting to increase threads or ensure some caching is enabled)? Currently I do no see much load but I expect some peaks next month and from what I see when a few people browse a story it is either very CPU intense or my CPU is too weak.

I also wonder how I could simulate some load to see what happens. I will see what I can do with jmeter maybe for that purpose.

Thanks and cheers,

**Comment by tf** [comment]
Hi,

using Memcached via [Dalli](https://github.com/mperham/dalli#usage-with-rails-3x-and-4x) is a good choice. Rails' default settings in `config/environments/production.rb` are fine in most cases. As for the `eager_load` option, in the doc comment it says:
```ruby
  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both thread web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true
```
So this option should be enabled in production.

Two important things for the production setup:

* Make sure you are using a CDN (see [this wiki page](https://github.com/codevise/pageflow/wiki/Setting-up-External-Services)). S3 is too slow to serve assets directly. Static assets should also be served by a CDN and not by your application. If you are expecting really high traffic, also consider serving your Pageflow entries though a CDN by using a [DNS to CDN setup](https://robots.thoughtbot.com/dns-cdn-origin). This is an advanced setup, though, that you are probably not going to need.
* If you are using Nginx, configure `ngixnx-upload-module` as described in this [wiki page](https://github.com/codevise/pageflow/wiki/Using-the-Nginx-Upload-Module). Ruby/Passenger is slow when it comes to parsing large uploaded files, which will block your passenger queue.
 
Most of this is not specific to Pageflow though. So concerning how to successfully deploy and run Rails applications, there is only a very limited amount of support we can offer here.

**Comment by thy1985** [comment]
hi tf,

thanks a lot for your feedback! It was very helpful.

Cheers,
