### ISSUE TITLE
Image Upload failed

### ISSUE THREAD

**Issue by madsirt** [codevise/pageflow#290]
Hi,

I have set up a test installation of pageflow. I finally got it running but now I have an issue regarding the image upload. It just would not do. When I try to upload an image I always get an “Upload failure”. It does not seem to work at all.

As I followed the installation guide from start to finish I do not know where the problem comes from. Unfortunately the failure message does not provide any extra information why it fails. And I also do not know where I could find such information as I do not see any logs or else.

Anybody an idea what the problem could be or where I should look for?

I would appreciate any help.

Cheers,
madsirt

**Comment by kioopi** [comment]
The setup for Zencoder/AWS is indeed a bit tricky.  Have you had a look atthe guide explaining the setup of these external services? 

https://github.com/codevise/pageflow/wiki/Setting-up-External-Services

**Comment by madsirt** [comment]
Hi kioopi,

yes indeed. I followed the instruction step by step and as I wrote Zencoder is working so far. It encodes the video and even sends it back to my S3 output bucket. And there it kinda breaks as Pageflow somehow cannot access/download the encoded video files from there.

**Comment by madsirt** [comment]
Hi kioppi,

yes indeed. I followed the instruction step by step. And for video it (almost) works. See my issue https://github.com/codevise/pageflow/issues/291. I do not know if the problems are related somehow.

**Comment by kioopi** [comment]
This seems like there is something wrong with the bucket policy of the output bucket.  There are two different policies for `main` and `output` bucket. 

The second one is the output bucket:

https://github.com/codevise/pageflow/wiki/Zencoder-Bucket-Policies

**Comment by madsirt** [comment]
Hi kioopi,
thanks for your help but I found the problem. It was the missing paket 'imageMagick'. As soon as I installed the paket the upload worked. And it was also the problem for my other issue (https://github.com/codevise/pageflow/issues/291).
So thanks again for your help. I appreciate it a lot.
Cheers,
madsirt

**Comment by kioopi** [comment]
Great!  We will try to document this better.
