### ISSUE TITLE
Video encoding is stuck at 98 %

### ISSUE THREAD

**Issue by madsirt** [codevise/pageflow#291]
Hi,

I have set up a test installation of pageflow. I finally got it running but now I have an issue regarding the video encoding. I am almost there.

What works is:
-	Upload to S3
-	Transfer to Zencoder
-	Encoding with Zencoder
-	Upload of the encoded video back to S3 (output bucket)

What does not work is:
-	Download from S3 to local Pageflow installation or access out of Pageflow on the encoded video

Here the process obviously breaks off. The progress bar stops at 98 %, but the wheel keeps on turning. So it looks like it is doing something. (I found a similar thread [https://github.com/codevise/pageflow/issues/69] a year ago where tyranny had the same problem. Unfortunately no solution for this specific problem is contained.)

When I checked the tmp folder I found that it actually downloaded the thumbnails create by Zencoder from S3 but no video. I just don not know what is the problem here. Or where/how to check.

Anybody an idea what the problem could be or where I should look for?

I would appreciate any help.

Cheers,
madsirt

**Comment by tyranni** [comment]
Hi madsirt,
yes, I remember that problem. After installing 'imageMagick' and restarting the server my problems were gone. But I don't know if this would help in your case too.
Best wishes!
tyranni

**Comment by madsirt** [comment]
Hi tyranni,
that was it. I installed 'imageMagick' and restarted Pageflow and now it works! That missing paket seemed to be the issue for both my problems, the stuck video encoding as well as the failed image upload (https://github.com/codevise/pageflow/issues/290). Would be good to highlight the importance of that paket in the Pageflow installation guide.
Thanks for your help. I apprecciate it a lot.
Cheers,
madsirt
