### ISSUE TITLE
Attachments are created by "nouser"

### ISSUE THREAD

**Issue by marcek** [codevise/pageflow#305]
Hi there,
I'm using pageflow version 0.8.0 and have problems with file permissions. Images are nicely uploaded to s3 buckets but I've just got stuck with videos. Files are placed in to tmp/attachments but created as "nouser" and "nogroup" what prevents pageflow from further processing.

I call resque via capistrano by: 
/usr/bin/env nohup ~/.rvm/bin/rvm my-rvm-ruby@my-rvm-gemset do bundle exec rake RAILS_ENV=production QUEUE="*" PIDFILE=/path/resque_work_1.pid BACKGROUND=yes VERBOSE=1 INTERVAL=5 environment resque:work >> log/resque.log 2>> log/resque.log

pid and log files are created by proper user. Video files always by 'nouser'.
Any idea what can be wrong ?

**Comment by tf** [comment]
Hi,

have to say, I'm not sure. Image files are uploaded to S3 directly in the request cycle. So resque is not involved there and your resque setup migth be the problem. I'd expect files to be owned by the user of the resque process. So if pid and log files have correct owners, that seems odd. Maybe there are other resque processes picking up jobs which run as different users?

**Comment by tf** [comment]
Did you figure out what causes the problem?

**Comment by marcek** [comment]
Yes, it took me a while because I was looking in a wrong place. It's a web server, in my case nginx, who is reponsible for putting files in tmp/attachments. 

```
server {
        listen       80;
        server_name  example.com;
        passenger_user user;
```

So the problem was caused by wrong user in ```passenger_user``` directive. Everything is fine. Pageflow works smoothly. Thanks.

**Comment by tf** [comment]
Happy to hear that.
