### ISSUE TITLE
Override pageflow root routes

### ISSUE THREAD

**Issue by AKNiazi** [codevise/pageflow#364]
Hello! I am trying to use pageflow on admin side and install a theme on the rails root route. but pageflow keeps redirecting me to active admin login page. I want to overwrite it. As you can see in the below link on line 49. It is redirecting to /admin. I want my app to stay on root route, i defined in routes.rb

https://www.omniref.com/ruby/gems/pageflow/0.6.0/files/config/routes.rb

Regards

**Comment by tf** [comment]
Hello Abdullah,

sorry for the late response. You could consider using [routing constraints](https://github.com/codevise/pageflow/wiki/Setting-up-Routing-Constraints) to serve the pageflow admin under a different hostname. It should also be possible to wrap the `Pageflow.routes` call in a `constraints` block to also restrict Pageflow's public routes to a special hostname.

Mounting Pageflow under a non-root URL using a [`namespace` block](http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing) has never been tried before and I'd expect it to require some changes. While not a priority for us at the moment, I'd be happy to give pointers if you decided to start experimenting with that approach.

**Comment by tf** [comment]
Any update here?
