### ISSUE TITLE
Consistently get errors when running test suite

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#402]
When I run the test suite I consistently get the error below.

It's because some database content is missing I think, most likely a built in widget type. `app/helpers/pageflow/entries_helper.rb:54` is involved and maybe others, it's not clear to me. I am just running `bin/rspec` here. Is there setup I am missing?

```
  13) Pageflow::EntriesController#show with format html with page parameter renders social sharing meta tags for page
     Failure/Error: get(:show, :id => entry, :page => page.perma_id)
     ActionView::Template::Error:
       undefined method `name' for nil:NilClass
     # ./app/helpers/pageflow/entries_helper.rb:54:in `block in entry_mobile_navigation_pages'
     # ./app/helpers/pageflow/entries_helper.rb:53:in `tap'
     # ./app/helpers/pageflow/entries_helper.rb:53:in `entry_mobile_navigation_pages'
     # ./app/views/pageflow/entries/_mobile_navigation.html.erb:10:in `___sers_joost__ems_pageflow_app_views_pageflow_entries__mobile_navigation_html_erb___3123839094170094754_70153508100120'
     # ./lib/pageflow/built_in_widget_type.rb:20:in `render'
     # ./app/helpers/pageflow/widgets_helper.rb:13:in `block in render_widgets'
     # ./app/helpers/pageflow/widgets_helper.rb:12:in `map'
     # ./app/helpers/pageflow/widgets_helper.rb:12:in `render_widgets'
     # ./app/views/pageflow/entries/_entry.html.erb:20:in `block in ___sers_joost__ems_pageflow_app_views_pageflow_entries__entry_html_erb__1665209415169336676_70153476364040'
     # ./app/views/pageflow/entries/_entry.html.erb:1:in `___sers_joost__ems_pageflow_app_views_pageflow_entries__entry_html_erb__1665209415169336676_70153476364040'
     # ./app/views/pageflow/entries/show.html.erb:21:in `block in ___sers_joost__ems_pageflow_app_views_pageflow_entries_show_html_erb___3761779584405099980_70153514336380'
     # ./app/views/pageflow/entries/show.html.erb:16:in `___sers_joost__ems_pageflow_app_views_pageflow_entries_show_html_erb___3761779584405099980_70153514336380'
     # ./spec/controllers/pageflow/entries_controller_spec.rb:262:in `block (5 levels) in <module:Pageflow>'
     # -e:1:in `<main>'
```

All test errors relate to a method being called on `nil` so I think they have the same cause.

**Comment by tf** [comment]
Hm. Not sure either. Did you try deleting `spec/dummy/` to have `bin/rspec` regenerate the app and database schema? Maybe something got out of sync.

    rm -r spec/dummy
    bin/spring stop # Spring does not like if its containing application goes away
    bin/rspec

**Comment by tilsammans** [comment]
No change unfortunately. I am using ruby-2.2.2 however (which works fine otherwise).

Output in [this gist](https://gist.github.com/tilsammans/556b6fe352f8f60fe706). The built-in widget is still the most obvious target I think, but not quite sure how to approach.

**Comment by tf** [comment]
At least regarding `reorder` there seem to be [Ruby 2.2 issues](https://github.com/activeadmin/activeadmin/issues/3733) in ActiveAdmin and/or Rails. Could you try to rerun with Ruby 2.1?

**Comment by tilsammans** [comment]
Okay, that is absolutely it. Ruby 2.1 works fine.

**Comment by tf** [comment]
Really strange, though. One of these days we have to look into updating some of the core dependencies (Rails, ActiveAdmin, Devise). That might be a good time to also resolve those incompatibility issues.

**Comment by tilsammans** [comment]
Yep. agreed that would be very welcome.
