### ISSUE TITLE
Copy of entry leads to broken page_links 

### ISSUE THREAD

**Issue by jrunkel** [codevise/pageflow#408]
When editing a copied entry with internal page links, the edit_page_link_view cannot be reached and therefore cannot be edited nor deleted. That is because the page_link reference is build like so: #pageid:#number_of_link. The #pageid is still the id of the copied page of the source entry, and not the id of the cloned page.

**Comment by tf** [comment]
This issue references features not yet merged on master. The bug has been fixed on the PR branch by now [referencing page perma ids](https://github.com/codevise/pageflow/pull/415/files#diff-277ed57da03794f2bd7a362962e4ce5fR76) instead.
