### ISSUE TITLE
"New Story" Button Visible for Editors

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#411]
When I create someone with role editor, they do see the link to create a new story, but when they click, they see "You are not authorized to perform this action.".

Either the link should not be visible, or editors should be allowed to create stories. I strongly prefer the latter, btw!

![schermafbeelding 2015-10-15 om 10 06 15](https://cloud.githubusercontent.com/assets/14680/10507941/622f757a-7324-11e5-9142-1beddb65b5ec.png)

**Comment by tf** [comment]
There are currently plans to extend the rights management by another role called "publisher", which allows creation and publication of entries within one's account, but does include other "account manager" rights like user management. Additionally, editors will no longer be allowed to publish entries.

So while giving editors the right to create entries, is not aligned with the workflows of some of our customers, it seems that the publisher role will pretty much meet your requirements.

For the moment, I'd happily accept a PR preventing the incorrect display of the "new entry" button.

If giving editors the ability to create new entries is important for your use case now (or even in the context of the planned rights system), it should be possible to add a line to your `app/models/ability` file like `can :create, Pageflow::Entry` to make that happen.

**Comment by tf** [comment]
FYI: I've changed the title of this issue to better reflect the bug aspect of the reported behavior.

**Comment by tilsammans** [comment]
That's okay. I didn't get round to fixing it.

**Comment by tilsammans** [comment]
I'm not sure what to do with `ViewComponent`.

Aan I add a `can? :create, Pageflow::Entry` [right here](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/views/components/pageflow/admin/entries_tab.rb#L12)?

**Comment by tf** [comment]
The `EntriesTab` is only used on the [account admin page](https://github.com/codevise/pageflow/blob/master/admins/pageflow/accounts.rb#L20) (via [this initializer](https://github.com/codevise/pageflow/blob/master/config/initializers/admin_resource_tabs.rb#L5)), which is only ever visible to admins.

The create link in the blank slate is Active Admin functionality. The missing authorization appears to have been [fixed upstream](https://github.com/activeadmin/activeadmin/commit/ecfb8bb04d2d85f16d46f2e36e2f9098e4195f6b). In [our "fork"](https://github.com/codevise/active_admin/tree/rails4) (which the README advises to use for Pageflow) this is [still missing](https://github.com/codevise/active_admin/blob/rails4/lib/active_admin/views/pages/index.rb#L126). 

Of the two commits our fork is ahead of the main line one has been pulled upstream and one is a backport. So there really is no real reason why we are still sitting on an old Active Admin snapshot. However there still is no released version that is Rails 4 compatible and depending on master feels risky.

**Comment by tf** [comment]
We could try to use `activeadmin 1.0.0.pre2` and see what breaks. But at least in [this issue](https://github.com/activeadmin/activeadmin/issues/4177) it seems like 1.0 could be right around the corner.

**Comment by tilsammans** [comment]
I could try out `1.1.0.pre2` on Thursday. We have a integration tests and should be able to confidently say if anything falls over. So I can report back at the end of the week.

**Comment by tf** [comment]
That sounds great!

**Comment by tilsammans** [comment]
It's not going to be smooth I'm afraid, see two patches below (application Gemfile and updated gemspec). Probably the biggest change is the necessary upgrade of Devise. I get this error, and will continue later in the week.

```
/Users/joost/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activesupport-4.1.12/lib/active_support/file_update_checker.rb:128:in `escape': undefined method `gsub' for ["/Users/joost/Gems/pageflow/admins"]:Array (NoMethodError)
```

### Gemfile

```patch
diff --git a/Gemfile b/Gemfile
index 8d8817e..611cb53 100644
--- a/Gemfile
+++ b/Gemfile
@@ -16,11 +16,11 @@ gem 'coffee-rails', '~> 4.0.0'
 gem 'jquery-rails'
 
 # gems we need
-gem 'pageflow'
-gem 'activeadmin', git: 'https://github.com/codevise/active_admin.git', branch: 'rails4'
+gem 'pageflow', path: '/Users/joost/Gems/pageflow'
+gem 'activeadmin', '1.0.0.pre2'
 gem 'ransack'
-gem 'inherited_resources', '1.4.1'
-gem 'formtastic', '2.3.0'
+gem 'inherited_resources'
+gem 'formtastic'
 gem 'state_machine', git: 'https://github.com/codevise/state_machine.git'
 gem 'figaro'
 gem 'whenever', require: false
```

### pageflow.gemspec

```patch
diff --git a/pageflow.gemspec b/pageflow.gemspec
index 31b3d4d..00447a3 100644
--- a/pageflow.gemspec
+++ b/pageflow.gemspec
@@ -14,13 +14,13 @@ Gem::Specification.new do |s|
 
   s.add_dependency 'rails', '>= 4.0.2', '< 4.2'
 
-  s.add_dependency 'activeadmin', '~> 0.6.0'
+  s.add_dependency 'activeadmin', '>= 1.0.0.pre2'
 
   # Make devise mailers use resque. (Needs to be below active admin entry!)
-  s.add_dependency 'devise-async', '~> 0.8.0'
+  s.add_dependency 'devise-async'
 
   # Caution: 3.1 changes methods used by Pageflow::InvitedUser
-  s.add_dependency 'devise', '~> 3.0.2'
+  s.add_dependency 'devise', '~> 3.2'
 
   # Resque jobs and queues
   s.add_dependency 'resque', '~> 1.25'
```

**Comment by tf** [comment]
Seems to be the same problem as [here](https://github.com/code-and-effect/effective_assets/pull/7). Looks like we need to splash when adding paths to the ActiveAdmin load path in our [Pageflow initializer](https://github.com/codevise/pageflow/blob/master/lib/generators/pageflow/initializer/templates/pageflow.rb#L2).

Regarding Devise update: In another project we found that the way [InvitedUser](https://github.com/codevise/pageflow/blob/master/app/models/pageflow/invited_user.rb) is implemented no longer works since now only an encrypted reset token is stored. Here's [a gitst](https://gist.github.com/tf/7dc139988642f4979c23) containing an alternative implementation. Sadly we had to copy over some parts of the [`set_reset_password_token`](https://github.com/plataformatec/devise/blob/v3.5.2/lib/devise/models/recoverable.rb#L101) method.

There are other solutions like [devise_invitable](https://github.com/scambra/devise_invitable) which I haven't looked into much. At first sight they seem like quite a heavy dependency for a relatively small problem though.

Thanks for investigating these updates!

**Comment by seanlinsley** [comment]
Hi there, I arrived here from the link to https://github.com/activeadmin/activeadmin/issues/4177. Please let me know if there are upgrade problems you encounter, so we can try and fix them before the official 1.0.0 release.

FWIW, I've used devise_invitable without too much trouble.

**Comment by tf** [comment]
@seanlinsley Thanks for reaching out and sorry for getting back to you so late! So far the update went quite well (#500). Changes were necessary, but nothing major. There are still a bunch of [deprecation warnings](https://travis-ci.org/codevise/pageflow/jobs/113100992) remaining. I'll report here, if something comes up that I cannot figure out.

**Comment by tf** [comment]
#500 is now merged.

**Comment by tilsammans** [comment]
That's great news! 🎉
