### ISSUE TITLE
Ability to completely hide navigation

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#413]
For some stories or even accounts we would like the ability to totally hide the navigation menu.

Is that possible? In the theme we can make it invisible, but it would be even better if the HTML were not generated in the first place. Also, hiding the navigation still leaves room for it on video pages.

**Comment by tf** [comment]
At least when more than one navigation widget is registered, the per entry widget select menus inside the editor and those on the account edit page should contain a "None" option. [We hide](https://github.com/codevise/pageflow/blob/master/app/assets/javascripts/pageflow/editor/views/edit_widget_view.js#L27) widget select boxes with only 1 widget type at the moment to prevent users from disabling widgets which only have a single default installed. Whether "None" is valid option should probably become part of the [widget type](https://github.com/codevise/pageflow/blob/master/lib/pageflow/widget_type.rb) [configuration](https://github.com/codevise/pageflow/blob/master/lib/pageflow/widget_types.rb) somehow.

Regarding the video page margin: At the moment, other alternative navigation widgets - like the progress navigation bar - [override video page specific styles](https://github.com/codevise/pageflow-progress-navigation-bar/blob/master/app/assets/stylesheets/pageflow/cross_dependant_styles.css.scss#L27) to remove the blank space. This should probably be the other way around: No margin by default and navigation bars defining margin as needed. 

Finally one might try to avoid coupling to specific CSS classes like `videoWrapper` in widget styles. I have some ideas here, but no final solution.
