### ISSUE TITLE
The installation instructions fail for mysql2

### ISSUE THREAD

**Issue by dertuxmalwieder** [codevise/pageflow#424]
Hi,

trying to follow the instructions does not work out well, it keeps failing on the `rake db:create` step:

> Gem::LoadError: can't activate mysql2 (~> 0.3.13), already activated mysql2-0.4.1. Make sure all dependencies are added to Gemfile.

I tried installing `mysql2` 0.3.13 but that did not solve anything.

Any ideas?

**Comment by tf** [comment]
Can you paste the contents of your Gemfile and Gemfile.lock into a gist? Also can you try to run `bundle exec rake` instead of just `rake` to see if that changes anything.

**Comment by dertuxmalwieder** [comment]
`bundle exec...` does not change anything, sadly.

`Gemfile`:

    source 'https://rubygems.org'
    
    
    # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
    gem 'rails', '4.2.4'
    # Use mysql as the database for Active Record
    gem 'mysql2', '0.4.1'
    # Use SCSS for stylesheets
    gem 'sass-rails', '~> 5.0'
    # Use Uglifier as compressor for JavaScript assets
    gem 'uglifier', '>= 1.3.0'
    # Use CoffeeScript for .coffee assets and views
    gem 'coffee-rails', '~> 4.1.0'
    # See https://github.com/rails/execjs#readme for more supported runtimes
    gem 'therubyracer', platforms: :ruby
    
    # Use jquery as the JavaScript library
    gem 'jquery-rails'
    # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
    gem 'turbolinks'
    # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
    gem 'jbuilder', '~> 2.0'
    # bundle exec rake doc:rails generates the API under doc/api.
    gem 'sdoc', '~> 0.4.0', group: :doc
    
    # Use ActiveModel has_secure_password
    # gem 'bcrypt', '~> 3.1.7'
    
    # Use Unicorn as the app server
    # gem 'unicorn'
    
    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development
    
    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'
    end
    
    group :development do
      # Access an IRB console on exception pages or by using <%= console %> in views
      gem 'web-console', '~> 2.0'
    
      # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
      gem 'spring'
    end

`Gemfile.lock`:

    GEM
      remote: https://rubygems.org/
      specs:
        actionmailer (4.2.4)
          actionpack (= 4.2.4)
          actionview (= 4.2.4)
          activejob (= 4.2.4)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 1.0, >= 1.0.5)
        actionpack (4.2.4)
          actionview (= 4.2.4)
          activesupport (= 4.2.4)
          rack (~> 1.6)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        actionview (4.2.4)
          activesupport (= 4.2.4)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.2)
        activejob (4.2.4)
          activesupport (= 4.2.4)
          globalid (>= 0.3.0)
        activemodel (4.2.4)
          activesupport (= 4.2.4)
          builder (~> 3.1)
        activerecord (4.2.4)
          activemodel (= 4.2.4)
          activesupport (= 4.2.4)
          arel (~> 6.0)
        activesupport (4.2.4)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        arel (6.0.3)
        binding_of_caller (0.7.2)
          debug_inspector (>= 0.0.1)
        builder (3.2.2)
        byebug (6.0.2)
        coffee-rails (4.1.0)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.4.1)
          coffee-script-source
          execjs
        coffee-script-source (1.9.1.1)
        debug_inspector (0.0.2)
        erubis (2.7.0)
        execjs (2.6.0)
        globalid (0.3.6)
          activesupport (>= 4.1.0)
        i18n (0.7.0)
        jbuilder (2.3.2)
          activesupport (>= 3.0.0, < 5)
          multi_json (~> 1.2)
        jquery-rails (4.0.5)
          rails-dom-testing (~> 1.0)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        json (1.8.3)
        libv8 (3.16.14.13)
        loofah (2.0.3)
          nokogiri (>= 1.5.9)
        mail (2.6.3)
          mime-types (>= 1.16, < 3)
        mime-types (2.6.2)
        mini_portile (0.6.2)
        minitest (5.8.1)
        multi_json (1.11.2)
        mysql2 (0.4.1)
        nokogiri (1.6.6.2)
          mini_portile (~> 0.6.0)
        rack (1.6.4)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (4.2.4)
          actionmailer (= 4.2.4)
          actionpack (= 4.2.4)
          actionview (= 4.2.4)
          activejob (= 4.2.4)
          activemodel (= 4.2.4)
          activerecord (= 4.2.4)
          activesupport (= 4.2.4)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.2.4)
          sprockets-rails
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.7)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.2)
          loofah (~> 2.0)
        railties (4.2.4)
          actionpack (= 4.2.4)
          activesupport (= 4.2.4)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (10.4.2)
        rdoc (4.2.0)
          json (~> 1.4)
        ref (2.0.0)
        sass (3.4.19)
        sass-rails (5.0.4)
          railties (>= 4.0.0, < 5.0)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (>= 1.1, < 3)
        sdoc (0.4.1)
          json (~> 1.7, >= 1.7.7)
          rdoc (~> 4.0)
        spring (1.4.0)
        sprockets (3.4.0)
          rack (> 1, < 3)
        sprockets-rails (2.3.3)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (>= 2.8, < 4.0)
        therubyracer (0.12.2)
          libv8 (~> 3.16.14.0)
          ref
        thor (0.19.1)
        thread_safe (0.3.5)
        tilt (2.0.1)
        turbolinks (2.5.3)
          coffee-rails
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (2.7.2)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        web-console (2.2.1)
          activemodel (>= 4.0)
          binding_of_caller (>= 0.7.2)
          railties (>= 4.0)
          sprockets-rails (>= 2.0, < 4.0)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      byebug
      coffee-rails (~> 4.1.0)
      jbuilder (~> 2.0)
      jquery-rails
      mysql2 (= 0.4.1)
      rails (= 4.2.4)
      sass-rails (~> 5.0)
      sdoc (~> 0.4.0)
      spring
      therubyracer
      turbolinks
      uglifier (>= 1.3.0)
      web-console (~> 2.0)
    
    BUNDLED WITH
       1.10.6

**Comment by tf** [comment]
Well, this is clearly not related to Pageflow since the pageflow gem does not even show up in your Gemfile. According to [this SO question](http://stackoverflow.com/questions/32543153/ruby-on-rails-cannot-connect-to-mysql-database) it's a [Rails bug](https://github.com/rails/rails/issues/21544) that can be worked around by downgrading mysql.

**Comment by tf** [comment]
Alright, I see now, that the failure occurred at the very first step of the install procedure - even before the gem has to be added. So sorry if I came off harsh. Still, try to follow the advice found in the SO post.

**Comment by dertuxmalwieder** [comment]
Downgrading MySQL does **not** work - I tried installing `mysql2` 0.3.13, it just was not recognized...

**Comment by tf** [comment]
So you changed the mysql2 gem version in your Gemfile to 0.3.13, ran `bundle install` and then `bundle exec rake db:create` still produced the same error message? Maybe try uninstalling mysql 0.4.x gems from your system.
