### ISSUE TITLE
can't upload file

### ISSUE THREAD

**Issue by silviupanaite** [codevise/pageflow#425]
Hi, 

I have setup the aws bucket but when I try to upload it hangs and the output doesn't show anything wrong. On the ui it says upload failed. Went through the troubleshoot, I use rails 4.1.10.

Started POST "/editor/entries/2/files/image_files" for 172.17.42.1 at 2015-10-28 12:12:57 +0000
Processing by Pageflow::Editor::FilesController#create as JSON
  Parameters: {"authenticity_token"=>"Pdg+NILhaTZgXxyX3vmC5kryukUGAa+51Qvqz5J+PYU=", "image_file"=>{"attachment"=>#<ActionDispatch::Http::UploadedFile:0x007effd0b8e288 @tempfile=#<Tempfile:/tmp/RackMultipart20151028-27819-1389mws>, @original_filename="Screen Shot 2015-10-24 at 09.55.37.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"image_file[attachment]\"; filename=\"Screen Shot 2015-10-24 at 09.55.37.png\"\r\nContent-Type: image/png\r\n">}, "entry_id"=>"2", "collection_name"=>"image_files"}
  User Load (0.1ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Pageflow::Entry Load (0.1ms)  SELECT  `pageflow_entries`.* FROM `pageflow_entries`  WHERE `pageflow_entries`.`slug` = '2'  ORDER BY `pageflow_entries`.`id` ASC LIMIT 1
  Pageflow::Entry Load (0.1ms)  SELECT  `pageflow_entries`.* FROM `pageflow_entries`  WHERE `pageflow_entries`.`id` = 2 LIMIT 1
  Pageflow::Revision Load (0.1ms)  SELECT  `pageflow_revisions`.* FROM `pageflow_revisions`  WHERE `pageflow_revisions`.`entry_id` = 2 AND (frozen_at IS NULL) LIMIT 1
  Pageflow::Entry Load (0.1ms)  SELECT `pageflow_entries`.* FROM `pageflow_entries` INNER JOIN `pageflow_memberships` ON `pageflow_entries`.`id` = `pageflow_memberships`.`entry_id` WHERE `pageflow_memberships`.`user_id` = 1
  Pageflow::EditLock Load (0.2ms)  SELECT  `pageflow_edit_locks`.* FROM `pageflow_edit_locks`  WHERE `pageflow_edit_locks`.`entry_id` = 2 LIMIT 1
  User Load (0.1ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 1 LIMIT 1
   (0.1ms)  BEGIN
  SQL (0.1ms)  UPDATE `pageflow_edit_locks` SET `pageflow_edit_locks`.`updated_at` = '2015-10-28 12:12:57' WHERE `pageflow_edit_locks`.`id` = 4
   (315.1ms)  COMMIT
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/a0a0b1c47cf4e5689a9d119026c78c1020151028-27819-nbopf7.png[0]' 2>/dev/null
   (0.3ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `pageflow_image_files` (`created_at`, `entry_id`, `height`, `state`, `unprocessed_attachment_content_type`, `unprocessed_attachment_file_name`, `unprocessed_attachment_file_size`, `unprocessed_attachment_updated_at`, `updated_at`, `width`) VALUES ('2015-10-28 12:12:57', 2, 1268, 'not_processed', 'image/png', 'Screen_Shot_2015-10-24_at_09.55.37.png', 329519, '2015-10-28 12:12:57', '2015-10-28 12:12:57', 1660)
[paperclip] saving 063d4e1d6155/image_files/unprocessed_attachments/000/000/007/original/Screen_Shot_2015-10-24_at_09.55.37.png

**Comment by tf** [comment]
Does the request hang at that point or does the log output go on? There might be something wrong with your S3 configuration causing the S3 save request to timeout. Since image upload to s3 happens in the request cycle this would cause the upload request in the browser to time out.

Have you looked at the [trouble shooting page](https://github.com/codevise/pageflow/wiki/Troubleshooting#error-message-in-pageflow-editor-during-image-upload-step). To say more, please post your paperclip config (with credentials removed).

**Comment by silviupanaite** [comment]
config.paperclip_s3_default_options.merge!(
    :s3_credentials => {
      :bucket => ENV.fetch('S3_BUCKET', 'dela0'),
      :access_key_id => ENV.fetch('S3_ACCESS_KEY', ‘xxx’),
      :secret_access_key => ENV.fetch('S3_SECRET_KEY', ‘xxx’),
      :s3_host_name => ENV.fetch('S3_HOST_NAME', 's3-website.eu-central-1.amazonaws.com')
    },
    :s3_host_alias => ENV.fetch('S3_HOST_ALIAS', 'dela0.s3-website.eu-central-1.amazonaws.com'),
    :s3_protocol => ENV.fetch('S3_PROTOCOL', 'http')
  )

**Comment by tf** [comment]
From the troubleshooting page:

> Check that you have used a valid s3_host_name in Pageflow's paperclip_s3_default_options setting. In particular, ensure that you are not using an s3-website. endpoint. Those are only for serving files from the bucket via HTTP - not for API access. See the [AWS list of regions and enpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) for possible values.

**Comment by silviupanaite** [comment]
Yes that was one issue, now upload files but it doesn't get stuck at retrying. I might not have setup correctly the permissions.
"Add the permissions View for Everyone for both buckets.
Go to Properties -> Permission
Click "Add more permissions"
Selecy "Everyone" from drop-down and click "View"
Save"
I can't find view. I have in the S3 bucket: list, upload/delete, view permissions, edit permissions.

**Comment by tf** [comment]
What do you mean by "it doesn't get stuck at retrying"? The required permission is called "List". I have updated the wiki page. I'll need a stack trace or log outout to help you find out what is wrong.

**Comment by silviupanaite** [comment]
Because I added the wrong S3 Host, rails output was hanging at paperclip upload.
 I added a new policy to my s3 IAM, full access and read only and I can see the files in the bucket, but now I get "processing failure". I have imagemagick installed (convert /tmp/20c7fdc29844bad93cb37223d1b1750a20151028-28598-pcrdbr.jpg -resize 64x64 resize_image.jpg does work).

**Comment by tf** [comment]
> Check log/jobs/development/resize.log to see why the job failed.

So what does it say?

**Comment by silviupanaite** [comment]
I, [2015-10-28T13:41:34.593436 #30782]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 17
I, [2015-10-28T13:41:36.457740 #30782]  INFO -- : Pageflow::ProcessImageFileJob - result error for Pageflow::ImageFile 17

**Comment by tf** [comment]
Hm. Ok that's not much. Did you restart the resque worker after updating your paperclip config?

**Comment by silviupanaite** [comment]
Restarting the rescue worker did solve the problem.

**Comment by tf** [comment]
:+1:
