### ISSUE TITLE
Analytics code

### ISSUE THREAD

**Issue by silviupanaite** [codevise/pageflow#439]
I have have tried what was said in the wiki but I couldn't get the analytics code to show, restarted the application and rescue workers.

**Comment by tf** [comment]
What exactly did you do?

**Comment by silviupanaite** [comment]
Edited this page, and added the analytics code pageflow/entries/_analytics.html.erb

**Comment by tf** [comment]
Well [here is the line](https://github.com/codevise/pageflow/blob/master/app/views/pageflow/entries/show.html.erb#L34)  where the partial is rendered. So placing the said file in the `app/views` directory of your Rails application should be enough. Are you running in production? Possible that [caching](https://github.com/codevise/pageflow/blob/master/app/views/pageflow/entries/show.html.erb#L16) prevents you from seeing the additional content?

**Comment by silviupanaite** [comment]
Did try to remove the cache, rake assets:clean, and clean the tmp directories... but couldn't get the code to show up.

Is there anything else I could try?

**Comment by tf** [comment]
It's not an asset cache, but a fragment cache. But this should not be
active when you are in development env. Does this also not work in
development env?

Silviu <notifications@github.com> schrieb am Do., 12. Nov. 2015 um
15:48 Uhr:

**Comment by silviupanaite** [comment]
irb(main):001:0> Rails.env.production? 
=> false

Can I migrate the development data into production?

**Comment by tf** [comment]
I mean how are you running your Pageflow app? Simply `rails s`? Or inside some Passenger setup?

**Comment by silviupanaite** [comment]
I use rails s.

**Comment by tf** [comment]
I need more information to help you find out why this is not working in your app. Can you push a minimal example app demonstrating the problem? Don't forget to remove any private credentials etc from your config files.

**Comment by silviupanaite** [comment]
Can you tell me what files are you looking for, so that I can make a dump of them.

**Comment by tf** [comment]
Well, mainly your `app/views/pageflow/entries` directory would be interesting as a first step.

**Comment by tf** [comment]
Feel free to reopen if the problem persists.
