### ISSUE TITLE
Update to Pageflow 0.9.1

### ISSUE THREAD

**Issue by gingko24** [codevise/pageflow#468]
Hello,

now I have updated my Development-Pageflow to 0.9.1. Bundle list shows following:

* pageflow (0.9.1)
 * pageflow-before-after (0.3.0)
 * pageflow-embedded-video (0.1.1)
 * pageflow-external-links (0.3.0)
 * pageflow-internal-links (0.1.0)
 * pageflow-text-page (0.2.0)

I have several problems with the new plugin pageflow-internal-links and I receive this error:
SyntaxError: File to import not found or unreadable: pageflow/internal_links/themes/default

I have access to the admin panel but I couldn´t find the new feature:
http://pageflow.tumblr.com/post/132019538353/kurz-vorm-winter-neue-features

Thanks for help

Joerg

**Comment by tf** [comment]
Hi Jörg,

The file that is missing in your case was only added after 0.1. If you look at [the Readme of v0.1](https://github.com/codevise/pageflow-internal-links/tree/v0.1.0/README.md) you'll notice it's not mentioned there.

Regarding new features: have you checked the Features tab on the account admin page?

**Comment by gingko24** [comment]
Thanks for your quick response,

sorry I can`t find the Features tab on the account admin page.

**Comment by tf** [comment]
But you do see the "entries" and "users" tabs? Are you sure you restarted the server? Do you have ` pageflow_default_abilities(user)` in your `app/models/ability.rb`?

**Comment by gingko24** [comment]
Yes, I see the "entries" and "users" tabs and I found this in app/models/ability.rb

  class Ability
  include CanCan::Ability
  include Pageflow::AbilityMixin

  def initialize(user)
    # Setup abilities for Pageflow models
    pageflow_default_abilities(user)

    # Allow signed-in users to view the admin dashboard
    can :read, ActiveAdmin::Page, :name => "Dashboard"
  end
end

**Comment by tf** [comment]
Huh, that has never come up before. Can you start `rails console` and run:

    Ability.new(User.find(123)).can?(:view, Pageflow::Admin::FeaturesTab)

where `123` is the id of your user account.

**Comment by gingko24** [comment]
Hello tf,
here is the output for the Admin-User:

Loading production environment (Rails 4.0.2)
irb(main):001:0> Ability.new(User.find(4)).can?(:view, Pageflow::Admin::FeaturesTab)
=> false

Thanks

**Comment by tf** [comment]
That should not be the case if user is admin. Please run `User.find(4).role` on the console.
