### ISSUE TITLE
Prevent/enforce SSL for editor and preview

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#469]
Back in #403, we introduced a mechanism to enforce or prevent HTTPS access to published entries. This is needed for example if your CDN does not support HTTPS. The same problem comes up though, also in the preview and the editor. So I was wondering if we should extend this behavior to also cover those cases. Only the name of the config option `public_ssl_mode` does not make that much sense then anymore. Maybe it should be a different option anyway?

@tilsammans how do you handle this at the moment? Would such a change also make sense in your case?

**Comment by tilsammans** [comment]
Our editor and preview are all on https and we don't encounter this issue.

I don't mind a broader implementation though. Currently we have one account that unfortunately cannot be served over http - their CNAME remains http. All others do have https, as has our own.

**Comment by tilsammans** [comment]
We've since migrated all our servers to [Let's Encrypt](https://letsencrypt.org) and even for the cnames not under our own control, we issue https certificates. I'm still cool with this change, though.

**Comment by tf** [comment]
Very interesting. I have to read up on that.

**Comment by tilsammans** [comment]
@tf what to do about this one? Should I mix in the filter into `Pageflow::ApplicationController` to make it global (if properly renamed)?

Or is the scope of this change actually outside the Rails app and should it be handled at earlier layers? We actually terminate SSL before Rails; not that I mind having this switch in the app. But arguably the front-end web servers are a better place?

**Comment by tf** [comment]
Good point. If it is a general redirect, it should probably live inside the front end server. 

The only setup I can think of that we could consider to support is if you want to use HTTPS for sign in pages only, because your CDN does not support HTTPS. We have to deal with this case for some of our instances. To handle this on the fronend server level one would have to hard code specific Devise routes inside the server config which seems sub optimal. So maybe this justifies adding the option. We would also have to cover the Active Admin case somehow. 

Maybe it would also be enough to only handle `Pageflow::EntriesController#edit` since it is the only non-admin route. Maybe we can keep the existing option and add `admin_ssl_mode` and `editor_ssl_mode`? Should `public_ssl_mode` then also apply to `Pageflow::RevisionsController#show`?

**Comment by tf** [comment]
To hook into Active Admin we already have [`Pageflow.active_admin_settings](https://github.com/codevise/pageflow/blob/master/lib/pageflow.rb#L23).

**Comment by tf** [comment]
We are also moving more towards full HTTPS coverage. The changes suggested here, thus, seem unnecessary.
