### ISSUE TITLE
Deleting Account does not delete Theming

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#476]
I might be mistaken, but I think account destroy does not get rid of the associated theming. There is no [dependent: :destroy](https://github.com/codevise/pageflow/blob/d9df7f627267d4d4d3dad0fc36c179df7985d28a/app/models/pageflow/account.rb#L9) on the relation.

This is problematic because in the Edit Entry screen, a [list of themings](https://github.com/codevise/pageflow/blob/master/admins/pageflow/entry.rb#L48) is needed for the theming dropdown. When a theming does not have a corresponding account, [line 23](https://github.com/codevise/pageflow/blob/master/app/models/pageflow/theming.rb#L23) raises `undefined method 'name' for nil:NilClass`.

*EDIT: Changed "Edit Account" to "Edit Entry" and inserted links -- @tf*

**Comment by tf** [comment]
You are correct and I guess you also mentioned the solution. A [similar problem exists for folders](https://github.com/codevise/pageflow/blob/bb5979e34948b75aa1995033b237e9ca92f6abf4/app/views/components/pageflow/admin/grouped_folder_list.rb#L84). So I think those are save to dependent destroy as well. For users and entries of the account the problem does not come up since only [empty accounts can be deleted](https://github.com/codevise/pageflow/blob/master/lib/pageflow/ability_mixin.rb#L41).

**Comment by tilsammans** [comment]
I'll create a pull request.

**Comment by tilsammans** [comment]
@tf i am having massive trouble getting the test suite to run locally. For days the `pageflow_storylines` table wouldn't get created using the dummy (4.0.4) app. Frustrated I finally went into the 4.0.4 app, copied the Pageflow migrations (they were indeed not present in the dummy app) and migrated. That at least fixed it, but now the `custom_field` column is missing.

Clearly the rails template is not executed and the dummy app is wildly incomplete. The trouble is, I don't see what I could be doing wrong. Using ruby 1.9.3 and the normal `bin/rspec`. I am doing everything like Travis, which passes, but for me nothing.

Any ideas?

**Comment by tf** [comment]
The Rails template is only used if the dummy app does not exist. Since it is git ignored this is always the case on Travis. Can you try to run:

    rm -r spec/dummy/*
    bin/spring stop # Spring does not like having its app deleted
    bin/rspec

Do you see any errors while the generator is running during test setup?

**Comment by tilsammans** [comment]
That's the trick ... I had an ancient dummy app in there.

**Comment by tf** [comment]
I've added a note to the test suite instructions in the [CONTRIBUTING.md](https://github.com/codevise/pageflow/blob/master/CONTRIBUTING.md) file.
