### ISSUE TITLE
Uploading image results in forever pending item

### ISSUE THREAD

**Issue by vetm73** [codevise/pageflow#507]
I do not see an error but when uploading it shows me pending forever and log shows

  SQL (1.6ms)  INSERT INTO `pageflow_image_files` (`created_at`, `entry_id`, `height`, `state`, `unprocessed_attachment_content_type`, `unprocessed_attachment_file_name`, `unprocessed_attachment_file_size`, `unprocessed_attachment_updated_at`, `updated_at`, `width`) VALUES ('2016-03-23 16:32:17', 1, 83, 'not_processed', 'image/png', 'hebban_dizzie_stats.png', 16241, '2016-03-23 16:32:17', '2016-03-23 16:32:17', 1356)
[paperclip] saving seventythree-websites/image_files/unprocessed_attachments/000/000/006/original/hebban_dizzie_stats.png

**Comment by tf** [comment]
Sounds like [this item](https://github.com/codevise/pageflow/wiki/Troubleshooting#error-message-in-pageflow-editor-during-image-upload-step) from the trouble shooting wiki page.

**Comment by vetm73** [comment]
Thank you so much. It is working now

Kind regards,

Mike
