### ISSUE TITLE
Pagetypes are missing

### ISSUE THREAD

**Issue by alaabatayneh** [codevise/pageflow#516]
Hi,

The hosted version of Pageflow comes with a big list of page types, while the version in Github comes only with few. How can we get the rest of pagetypes?

**Comment by jrunkel** [comment]
Many pagetypes are distributed as plugins. See the codevise github repositories list. We should mention that more prominent in the docs though.

**Comment by tf** [comment]
See also https://github.com/codevise/pageflow/wiki/List-of-Plugins
