### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by railization** [codevise/pageflow#519]
Guys,
For google analytics do we have to develop a plugin ? Or how it gonna work? 

Best regards,

Arsalan

**Comment by tf** [comment]
Hi Arsalan,

the most basic approach would be to [override the `_analytics.html.erb` partial](https://github.com/codevise/pageflow/wiki/Customizing-Views) and paste an google analytics snippet there. In all but the simplest cases, I'd recommend [defining a Pageflow widget type](https://github.com/codevise/pageflow/blob/master/doc/creating_widget_types.md), though. There's an open source example in the [scrollytelling app](https://github.com/scrollytelling/app) by @tilsammans (see [widget type definition](https://github.com/scrollytelling/app/blob/master/app/models/widgets/analytics.rb), [widget type template](https://github.com/scrollytelling/app/tree/master/app/views/widgets/analytics/amnesty) and [widget type registration](https://github.com/scrollytelling/app/blob/master/config/initializers/pageflow.rb#L26)). Far as I know, @tilsammans is also working on a more generic analytics widget type plugin. Maybe you can join forces?

**Comment by tilsammans** [comment]
I didn't go any further than @tf is describing, but you can definitely look at my code.

I have independent analytics widgets on an account basis and it works very well. The generic plugin is going to be a little ways off, but when I find some spare time I will look into it.

**Comment by railization** [comment]
Hi Tim,

I really appreciate your support on GA. Let me talk with my client and then we could come up with a solution. 

Thanks,

Arsalan

**Comment by tf** [comment]
Great. I'll close this issue for now. Feel free to comment here if further questions come up and I'll re-open the issue.
