### ISSUE TITLE
Allow themes to include JavaScript

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#537]
For some of our themes I find myself wanting to include JavaScript. There are just some cases where it's handy to have full control. Instead of having to inline it would be nice if Pageflow were to consider JavaScript for themes as well. A theme could (optionally) include an asset pipeline backed JavaScript file.

Themes would then become a collection of JS + CSS instead of just CSS.

Because it's easy to make a royal mess this should probably be left to advanced customisers only and come with some warnings?

**Comment by tf** [comment]
Can you give an example what such theme JS would do?

**Comment by tilsammans** [comment]
We have some cases where we want to add a class after Pageflow loads, it depends on a CSS class being present in the theme:

```javascript
pageflow.ready.then(function() {
  $('body').addClass('finished-loading');
});
```

We are currently [inlining](https://github.com/scrollytelling/app/blob/78cca3c8f518ea11a83ae0df6cb2d4dbcb6b66f9/app/views/pageflow/entries/_navigation.html.erb) all JS related to our version of the navigation. This would apply to all of our themes, so I guess it could become a widget?

Analytics would be a good candidate for theme-specific JS as well. An analytics account is always tied 1-to-1 to a theme. Our current feature widgets work fine but the list is already becoming [pretty long](https://github.com/scrollytelling/app/blob/78cca3c8f518ea11a83ae0df6cb2d4dbcb6b66f9/config/initializers/pageflow.rb#L26).

**Comment by tf** [comment]
I'm a bit reluctant here. My recent work on Pageflow themes has lead me in the direction of rather increasing the isolation level of components like widgets and page types. So far our themes were highly coupled to implementation details like class names and DOM structure. To improve maintainability, I started introducing SCSS variables as a sort of public interface of widgets/page types. Ideally themes will mainly consist of SCSS variable assignments in the future.

With theme specific JS, I fear giving up this isolation again. I think we already have different options:

* As you said, many cases can be handled via widgets 
* We already have [theme options](https://github.com/codevise/pageflow/blob/master/lib/pageflow/themes.rb#L35) which can enable/disable certain JS functionality for individual themes. There could also be widget/page type specific theme options in the future if we think of a way to prevent name collisions.
* High level concepts like `finished_loading` can simply be general Pageflow functionality available to all themes.

Regarding your long list of theme specific widget types: For similar cases we have used widgets which dynamically build partial paths using `entry.theming.theme_name` as a path segment. If it's really a 1-to-1 relation, that works fine.

There is one more general issue that I see: Giving an increasing number of widget and page types, with the current setup, we always need to deliver all the JS/CSS even if only a subset of the available components is used. If this were to become a real issue at some point, we would have to look into generating assets more dynamically. Still theme specific JS would also not suffice as a solution.

**Comment by tilsammans** [comment]
Sure, makes sense. More docs about these things would be helpful; widgets to me are still pretty obscure and they're impossible to manage through the editor, right? Until now I've been updating raw DB records when I needed to apply widgets to published stories ... and also removing them when the copy task copied them over.

**Comment by tf** [comment]
We sure need more documentation. Still, I'd like to know more about the obstacles you are facing when managing widgets. For me there have mainly been three scenarios which all worked ok out of the box:

- Widgets are registered with the default option in the initializer and are always displayed for all entries 
- Default widgets are selected per theming in the account form, new entries in the account are setup with these defaults
- There are multiple widgets for the editor to choose from (i.e. navigation bars). Inside the editor users can select the desired widget via "Options > Appearance".

The only thing that has been annoying sometimes, is the fact that select boxes for widget roles which just one widget type (i.e. if there is one registered type of analytics widget) are hidden in the editor. This made it harder to retroactively enable a widget type for an existing entry.

**Comment by tilsammans** [comment]
> Widgets are registered with the default option in the initializer and are always displayed for all entries

You see I just don't see that. But it could be caching. I just deployed an entirely new `WidgetType` with the default option on and it definitely did _not_ appear in the story. Should it be rendered in the preview? Or do I have to publish for it to become available?

**Comment by tf** [comment]
It should be rendered everywhere directly by default. The only thing I can think of right now would be if you register a new widget type with a role that already existed before - like "navigation". That way all the existing entries will already have widgets for that role in the DB. Those then [take precedence](https://github.com/codevise/pageflow/blob/master/app/models/pageflow/widget.rb#L53).

**Comment by tilsammans** [comment]
I will do more tests and gather all the information that I can. Thank you.

**Comment by tilsammans** [comment]
It was a cache issue.
