### ISSUE TITLE
Generate Procfile

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#539]
Would you be interested if I tweaked the generator, to generate a Procfile in the root?

It would look something like this:

```
web: bundle exec rails server
worker: bundle exec rake resque:work QUEUE=*
scheduler: bundle exec rake resque:scheduler QUEUE=*
```

We can get rid of the verbose instructions in the README then.

**Comment by tf** [comment]
One would still need to mention foreman, right? Or would we also install that via the generator somehow?

**Comment by tilsammans** [comment]
It would still have to be mentioned and installed manually, for local development. I'm cool with that.

**Comment by tf** [comment]
Sounds fine to me.
