### ISSUE TITLE
Allow non S3 Storage for Image Files

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#54]
As discussed in #47, it is already possible to configure SFTP output for Zencoder jobs. This allows to serve video and audio files from a custom location avoiding S3 access in production. To store image files in a custom location, one could override  `config.paperclip_s3_default_options` to use filesystem storage. But at the moment this would break video/audio transfer to Zencoder since `paperclip_s3_default_options` is used by both `ImageFile#processed_attachment` and `VideoFile#attachment_on_s3`. Filesystem storage for video files does not make sense though since S3 is the only Zencoder input channel supported by Pageflow at the moment.

To resolve this problem, there needs to be a config option like `paperclip_processed_image_file_default_options` to specify the storage adapter used by `ImageFile#processed_attachment`.

The most complicated aspect probably is figuring out how to improve naming in this area. There needs to be a coherent naming scheme for these more fine grain options. Moreover, attachment names like `attachment_on_s3` already code to much information about implementation details. This could be fixed in this context. Finally, the default configuration should not become more complicated. For the default setup, the S3 storage options should only be defined in one place.

**Comment by din0715** [comment]
I can not upload the images to s3. 
I set both paperclip_processed_image_file_default_options and config.zencoder_options.merge!, but when uploading the images, upload url is localhost:3000/editor/entries/...
![screen shot 2019-02-27 at 11 18 09 am](https://user-images.githubusercontent.com/46061736/53463307-7fc01e00-3a81-11e9-9fd5-837d523ef6ac.png)

**Comment by tf** [comment]
Given that we now depend on direct upload to S3, this no longer seems feasible.
