### ISSUE TITLE
Bundle install fails

### ISSUE THREAD

**Issue by marcoreinke** [codevise/pageflow#582]
During the installation `bundle install` fails with the error `Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'meta_search' and try again.`

This is caused by activeadmin 0.6.0 and is fixed with the version 1.0. The problem: Pageflow expects Rails 4.0 or 4.1, but all versions of Rails >= 4.0.0 are throwing this error. This makes the installation impossible.

BTW: The gem "meta_search" is not installed.

**Comment by tf** [comment]
Please paste your `Gemfile` and `Gemfile.lock` (if that exists) into a gist and post a link.

**Comment by marcoreinke** [comment]
Thank you very much already for having a look on it: https://gist.github.com/marcoreinke/2785a41221c6722262623097c2bffa51

**Comment by tf** [comment]
On `master` Active Admin [has already been updated to `1.0.0-pre2`](https://github.com/codevise/pageflow/blob/master/pageflow.gemspec#L18). The latest released Pageflow version 0.10 still uses Active Admin from a `rails4` branch and requires additional `Gemfile` entries. Please take a look at [the readme on `0-10-stable`](https://github.com/codevise/pageflow/blob/0-10-stable/README.md#installation) for the required steps.

**Comment by marcoreinke** [comment]
"Wer lesen kann, ist klar vorn" - thanks a lot! I will close this issue.
