### ISSUE TITLE
Updating from pageflow 0.9.2 failed

### ISSUE THREAD

**Issue by wake666** [codevise/pageflow#595]
I followed the steps according to https://github.com/codevise/pageflow/wiki/Updating-Pageflow. 
Problems occur during the following steps:

- Increasing Pageflow version in Gemfile: 
  actually there isn't any reference to my current pageflow version in Gemfile.

- Changing the asset version: 
in my config/initializers/assets.rb there is
Rails.application.config.assets.version = '1.0'
Should I really put '0.x' as suggested in the instructions?

- After restarting the app, opening the editor throws an error.

My console output (Firefox developer tools):
GET http://pf.wake.works/entries/test/edit [HTTP/1.1 200 OK 705ms]
GET http://pf.wake.works/assets/pageflow/application-5bcfbc904280a2408f0ac9a4b13dee73.js [HTTP/1.1 200 OK 491ms]
GET http://pf.wake.works/assets/pageflow/application_with_simulated_media_queries-facd51a4987a1206420f3a32f2494cc4.css [HTTP/1.1 200 OK 274ms]
GET http://pf.wake.works/assets/pageflow/themes/default-45214b9575b5ff8bab1e0537fe4c74be.css [HTTP/1.1 200 OK 257ms]
GET http://pf.wake.works/revisions/77.css [HTTP/1.1 200 OK 395ms]
GET http://pf.wake.works/assets/pageflow/editor-8f27875967d92412eeae02392ceead5c.css [HTTP/1.1 200 OK 315ms]
GET http://pf.wake.works/assets/pageflow/editor-c41c5d6d745773d437b40c9583f61512.js [HTTP/1.1 200 OK 863ms]
GET http://pf.wake.works/assets/pageflow/print_view-ced1865611427b98d0b9494998e97f34.css [HTTP/1.1 200 OK 272ms]
Die Vollbild-Schnittstelle mit Präfix sollte nicht mehr verwendet werden. Bitte verwenden Sie die Variante ohne Präfix für den Vollbildmodus. Weitere Hilfe auf https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API application-5bcfbc904280a2408f0ac9a4b13dee73.js:7:23726
GET XHR http://pf.wake.works/editor/entries/6/seed [HTTP/1.1 500 Internal Server Error 249ms]
GET http://serve.pf.wake.de.s3-website-eu-west-1.amazonaws.com/bandwidth_probe_small.png [HTTP/1.1 200 OK 113ms]
GET http://serve.pf.wake.de.s3-website-eu-west-1.amazonaws.com/bandwidth_probe_large.png [HTTP/1.1 200 OK 1077ms]
Detected bandwidth 1102.9390759277344KB/s. High: Yes application-5bcfbc904280a2408f0ac9a4b13dee73.js:9:19826
  
Gemfile.lock and an excerpt of my production.log und are in attachment.

[Gemfile.lock.txt](https://github.com/codevise/pageflow/files/422110/Gemfile.lock.txt)
[production.log.txt](https://github.com/codevise/pageflow/files/422109/production.log.txt)

**Comment by tf** [comment]
Hello wake666,

* If you there is no version constraint in the `Gemfile`, there is nothing that needs to be changed.
* `x` is a placeholder for the number you are supposed to increase. So if the asset version was `1.0` before, make it `1.1`.

I've updated the wiki page regarding these two points, trying to make it more specific.

If you take a look at your log file, it says:

    undefined method `author' for #<Pageflow::Revision:0x007fb00994dea8>

It looks like you did not install migrations or did not migrate the database, as outlined in the wiki page.

**Comment by tilsammans** [comment]
Yes, if you run this:

```
bundle exec rake pageflow:install:migrations
bundle exec rake db:migrate
```

it should work better. 

@tf there is actually a [trick to append engine migrations onto the main app](https://blog.pivotal.io/labs/labs/leave-your-migrations-in-your-rails-engines). We use this for other apps that have been broken down into engines. It works really well, we don't give migrations any second thought any more. The blog post mentions monkey patching, but it's misleading I think as it uses a documented hook for Rails 4.

Since Pageflow's migrations *must* always run this should save some upgrading pain.

```
module EngineWithMigrations
  class Engine < ::Rails::Engine
    isolate_namespace EngineWithMigrations

    initializer :append_migrations do |app|
      unless app.root.to_s.match root.to_s
        config.paths["db/migrate"].expanded.each do |expanded_path|
          app.config.paths["db/migrate"] << expanded_path
        end
      end
    end
  end
end
```

**Comment by tf** [comment]
@tilsammans Interesting. I did not know about this possibility. Still, it feels a bit dangerous. Especially when deploying production systems, I actually like the explicitness of having the migrations right there for inspection in my `db/migrate` directory.

There is also `bundle exec rake railties:install:migrations`, which copies migrations for all engines. Maybe we should use that in the wiki page as there might be other Pageflow plugins that also bring migrations.

**Comment by tilsammans** [comment]
Agreed on both counts.

The engines we use it for are internal ones, and the implications are known by everyone.

**Comment by wake666** [comment]
Thank you so far for your help!
 I actually did run
```
bundle exec rake pageflow:install:migrations
bundle exec rake db:migrate
```
This didn't prevent the error above when starting the editor.

**Comment by tf** [comment]
Then I need a directory listing of your `db/migrate` folder and the shell output of running the two mentions commands when you run them now.

**Comment by tf** [comment]
@tilsammans I've updated the wiki page to use the alternative rake task.

**Comment by wake666** [comment]
`bundle exec rake railties:install:migrations`
```
Copied migration 20160819054257_create_pageflow_storylines.pageflow.rb from pageflow
Copied migration 20160819054258_add_storyline_id_to_chapters.pageflow.rb from pageflow
Copied migration 20160819054259_insert_main_storylines.pageflow.rb from pageflow
Copied migration 20160819054260_remove_revision_id_from_chapters.pageflow.rb from pageflow
Copied migration 20160819054261_remove_entry_id_from_chapters.pageflow.rb from pageflow
Copied migration 20160819054262_add_additional_cnames_to_themings.pageflow.rb from pageflow
Copied migration 20160819054263_add_meta_fields_to_revision.pageflow.rb from pageflow

```
`bundle exec rake db:migrate`
```
== 20160819054257 CreatePageflowStorylines: migrating =========================
-- create_table(:pageflow_storylines)
   -> 0.0292s
== 20160819054257 CreatePageflowStorylines: migrated (0.0293s) ================

== 20160819054258 AddStorylineIdToChapters: migrating =========================
-- add_column(:pageflow_chapters, :storyline_id, :integer)
   -> 0.0063s
-- add_index(:pageflow_chapters, [:storyline_id], {:name=>"index_pageflow_chapters_on_storyline_id", :using=>:btree})
   -> 0.0084s
== 20160819054258 AddStorylineIdToChapters: migrated (0.0149s) ================

== 20160819054259 InsertMainStorylines: migrating =============================
-- execute("      INSERT INTO pageflow_storylines\n        (perma_id, revision_id, position, configuration, created_at, updated_at)\n        SELECT entry_id, id, 1, '{\"main\":true}', created_at, updated_at\n        FROM pageflow_revisions\n")
   -> 0.0015s
-- execute("      UPDATE pageflow_chapters SET storyline_id =\n        (SELECT id FROM pageflow_storylines\n         WHERE pageflow_storylines.revision_id = pageflow_chapters.revision_id)\n")
   -> 0.0023s
== 20160819054259 InsertMainStorylines: migrated (0.0040s) ====================

== 20160819054260 RemoveRevisionIdFromChapters: migrating =====================
-- remove_column(:pageflow_chapters, :revision_id)
   -> 0.0039s
== 20160819054260 RemoveRevisionIdFromChapters: migrated (0.0040s) ============

== 20160819054261 RemoveEntryIdFromChapters: migrating ========================
-- remove_column(:pageflow_chapters, :entry_id)
   -> 0.0046s
== 20160819054261 RemoveEntryIdFromChapters: migrated (0.0047s) ===============

== 20160819054262 AddAdditionalCnamesToThemings: migrating ====================
-- add_column(:pageflow_themings, :additional_cnames, :string)
   -> 0.0037s
== 20160819054262 AddAdditionalCnamesToThemings: migrated (0.0038s) ===========

== 20160819054263 AddMetaFieldsToRevision: migrating ==========================
-- add_column(:pageflow_revisions, :author, :string)
   -> 0.0039s
-- add_column(:pageflow_revisions, :publisher, :string)
   -> 0.0041s
-- add_column(:pageflow_revisions, :keywords, :string)
   -> 0.0042s
== 20160819054263 AddMetaFieldsToRevision: migrated (0.0124s) =================
```
`ls -la db/migrate`
```
drwxrwxr-x 2 pageflow pageflow 4096 Aug 19 07:42 .
drwxrwxr-x 3 pageflow pageflow 4096 May 10 21:58 ..
-rw-rw-r-- 1 pageflow pageflow  591 May 10 21:55 20160510195519_create_active_admin_comments.rb
-rw-rw-r-- 1 pageflow pageflow 1482 May 10 21:55 20160510195524_devise_create_users.rb
-rw-rw-r-- 1 pageflow pageflow  567 May 10 21:55 20160510195528_create_friendly_id_slugs.rb
-rw-rw-r-- 1 pageflow pageflow 8967 May 10 21:55 20160510195542_setup_schema.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  694 May 10 21:55 20160510195543_add_attributes_to_users.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  401 May 10 21:55 20160510195544_create_themings.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow 1205 May 10 21:55 20160510195545_create_themings_for_existing_accounts.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow 1837 May 10 21:55 20160510195546_change_theme_references_to_theming_references.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  460 May 10 21:55 20160510195547_remove_attributes_from_themes.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  273 May 10 21:55 20160510195548_create_accounts_themes_join_table.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  904 May 10 21:55 20160510195549_move_cname_from_account_to_theming.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  510 May 10 21:55 20160510195550_drop_themes.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  259 May 10 21:55 20160510195551_add_confirmed_by_to_encoded_files.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  526 May 10 21:55 20160510195552_add_home_url_attributes_to_themings_and_revisions.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  298 May 10 21:55 20160510195553_create_widgets.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  264 May 10 21:55 20160510195554_add_emphasize_chapter_beginning_to_revisions.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  248 May 10 21:55 20160510195555_add_emphasize_new_pages_to_revisions.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  331 May 10 21:55 20160510195556_add_sharing_image_to_revisions.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  177 May 10 21:55 20160510195557_add_locale_to_users.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  194 May 10 21:55 20160510195558_add_locale_to_revisions.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  204 May 10 21:55 20160510195559_add_configuration_to_chapters.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  221 May 10 21:55 20160510195560_add_features_configuration_to_accounts.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  219 May 10 21:55 20160510195561_add_features_configuration_to_entries.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  279 May 10 21:55 20160510195562_add_password_attributes_to_revisions.pageflow.rb
-rw-rw-r-- 1 pageflow pageflow  454 May 10 21:55 20160510195563_add_first_published_at_to_entries.pageflow.rb
-rw-r--r-- 1 root     root      340 Aug 19 07:42 20160819054257_create_pageflow_storylines.pageflow.rb
-rw-r--r-- 1 root     root      318 Aug 19 07:42 20160819054258_add_storyline_id_to_chapters.pageflow.rb
-rw-r--r-- 1 root     root      944 Aug 19 07:42 20160819054259_insert_main_storylines.pageflow.rb
-rw-r--r-- 1 root     root      200 Aug 19 07:42 20160819054260_remove_revision_id_from_chapters.pageflow.rb
-rw-r--r-- 1 root     root      194 Aug 19 07:42 20160819054261_remove_entry_id_from_chapters.pageflow.rb
-rw-r--r-- 1 root     root      213 Aug 19 07:42 20160819054262_add_additional_cnames_to_themings.pageflow.rb
-rw-r--r-- 1 root     root      308 Aug 19 07:42 20160819054263_add_meta_fields_to_revision.pageflow.rb
```

**Comment by tf** [comment]
As you can see from the output of the `rake db:migrate` command, running the migrations actually added the `author` field to the `pageflow_revisions` table, so the error found in the log file that you posted (`undefined method `author' for #<Pageflow::Revision:0x007fb00994dea8>`) has to be fixed now. If the editor still does not start, then something else is wrong and you need to take another look at what is printed to your log file or the browser console now.
