### ISSUE TITLE
Redirect back to features tab on after saving feature settings

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#623]
Just like in #621, hitting the "Save" button on [the features tab](https://github.com/codevise/pageflow/blob/master/app/views/components/pageflow/admin/features_tab.rb) of either an entry or an account admin page also does not redirect to the correct tab.

**Comment by DanielKuhn** [comment]
Fixed in #ba123a24701a90a384dedf1538b6aafe439764ce
