### ISSUE TITLE
plugins are missing translations

### ISSUE THREAD

**Issue by robelix** [codevise/pageflow#630]
After install all plugins can't find any translations

![pageflow-translations](https://cloud.githubusercontent.com/assets/407056/18588438/bf886cc0-7c26-11e6-8245-0cecf573d09e.png)

How to fix that?

**Comment by tf** [comment]
Have you tried https://github.com/codevise/pageflow/wiki/Troubleshooting#missing-translations-in-editor ?

**Comment by robelix** [comment]
rake assets:precompile did the job - after I got it working again (had some scss-bugs)

**Comment by tf** [comment]
Ok. Glad to hear.
