### ISSUE TITLE
Appear to be missing Active_Admin CSS

### ISSUE THREAD

**Issue by jtebbenGS** [codevise/pageflow#635]
I just did a fresh install of pageflow (Gemfile attached) and everything appears to work except the CSS (possibly javascript as well) are getting a rount error (see image).  All of the pageflow resources appear to be intact, but the admin sections look plain.

I am completely new to Ruby\Rails\Gems but believe I am close here. Any feedback is greatly appreciated.
Or if I'm missing some details

![image](https://cloud.githubusercontent.com/assets/22460270/18854912/457e6b32-8414-11e6-89b6-fafec2169b46.png)
[gemfile_pageflow.txt](https://github.com/codevise/pageflow/files/494274/gemfile_pageflow.txt)

**Comment by tf** [comment]
Hi,

* How did you get to this url? Far as I know, there is no `assets/active_admin/active_admin.css` only `assets/active_admin.css`.
* Do you see an error (i.e. a 404) in the browser dev tools when viewing an admin page? What does the error message say exactly?
* Is this a production or development environment?

**Comment by jtebbenGS** [comment]
I got this url via the browser console showing an attempt was made and failed to get this url. This occurred when I attempted to run the Production only environment (via: ben@pagefl-t1m1:RAILS_ENV=production rails s ).

When I simply run  "ben@pagefl-t1m1: rails s" I don't get any 404s, however the style still isn't applied to the admin section of the site (see image below). Its as if the "active_admin" assets have not been pulled down. 

![image](https://cloud.githubusercontent.com/assets/22460270/18874044/75118348-8487-11e6-922b-4483859042af.png)

**Comment by tf** [comment]
* In production environment the assets have to be served by your Nginx or Apache (unless you activated `config.serve_static_assets` in your `config/environments/production.rb`). Please check the contents of `public/assets/active_admin-<some_hash>.css` which should be generated when precompiling assets (i.e. `bin/rake assets:precompile`).

* It's strange though, that it's not working in development mode. The Pageflow install generator should have created `app/assets/stylesheets/active_admin.scss` with at least the following imports:

        @import "active_admin/mixins";
        @import "active_admin/base";
        @import "pageflow/admin";

  In your development server you should see a request for `/assets/active_admin-<some_hash>.css`     which should respond with the rendered CSS.

**Comment by jtebbenGS** [comment]
This is the stylesheet being server up and it does have the @import statements called out above
assets/active_admin.css?body=1

I must have missed something in the documentation, where are the "Nginx or Apache" requriement\setup processes called out?

**Comment by tf** [comment]
Can you paste the HTML (mainly the `<head>` section is interesting) and the contents of all referenced stylesheets into a gist, so I can get a better picture of the situation?

**Comment by tf** [comment]
Regarding the Nginx/Apache requirements. That's not Pageflow specific, but rather the way all Rails applications are deployed. Setup instructions can either be found in the [Passenger](https://www.phusionpassenger.com) docs or the documentation provided by your hosting provider/deployment solution.

**Comment by jtebbenGS** [comment]
Ok, I had a feeling I wasn't fully getting Rails. I'm kind of in a trial by fire situation. Good news is the only piece that appears to be missing is the active_admin css, the pageflow is up and getting a lot of love by the users, so kudos.

Here is the full head tag per your previous message:

[html_extract.html.txt](https://github.com/codevise/pageflow/files/511186/html_extract.html.txt)

**Comment by tf** [comment]
But `http://localhost:3000/assets/active_admin.css?body=1` is empty or what is its contents?

**Comment by jtebbenGS** [comment]
It exists, here are the contents
[html_extract.html.txt](https://github.com/codevise/pageflow/files/511195/html_extract.html.txt)

**Comment by tf** [comment]
If this is what you see in the browser, then the asset pipeline inside your Rails application appears to be misconfigured somehow. SCSS has not been compiled, otherwise you would see a file with plain CSS and no imports.

**Comment by jtebbenGS** [comment]
Am I calling out the wrong sass-rails version in my GemFile?

--- extract ---
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

**Comment by tf** [comment]
That should be ok. Pageflow itself depends on `sass-rails`. So just to get the facts straight: You have a file called `app/assets/stylesheets/active_admin.css.scss` or `app/assets/stylesheets/active_admin.scss` (the important part is the extension is "scss"), but when you display `/assets/active_admin.css` in your browser you see the `@import` statements.
