### ISSUE TITLE
Updated to 0.11.3 - db:migrate now failing

### ISSUE THREAD

**Issue by jtebbenGS** [codevise/pageflow#672]
I am attempting to update the install of pageflow to version 0.11.3, I update the Gemfile and created the migration db/migrate/* files, but the call to run the migration results in the following

 `jtebben@pagefl-t1m1:/var/www/vivo_pf$ bundle exec rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `gsub' for ["/var/lib/gems/2.1.0/gems/pageflow-0.11.3/admins"]:Array
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:128:in `escape'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:122:in `block in compile_glob'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:121:in `each'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:121:in `map'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:121:in `compile_glob'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:40:in `initialize'
/var/lib/gems/2.1.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:299:in `new'
/var/lib/gems/2.1.0/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:299:in `block in attach_reloader'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:36:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/var/www/vivo_pf/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/var/lib/gems/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `each'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/var/lib/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
jtebben@pagefl-t1m1:/var/www/vivo_pf$
`

Any help would be appreciated. Note that I already following the troublshooting around the mis-named ".rb" files in the migrate folder.

**Comment by tf** [comment]
Looks like you might not have performed the manual update step for the Active Admin load path described in point 2 of the ["Breaking Changes" section for Version 0.11 in the changelog](https://github.com/codevise/pageflow/blob/master/CHANGELOG.md#breaking-changes):

> Active Admin/Devise have been updated. The gem entries for activeadmin, ransack, inherited_resources and formtastic have to be removed. Furthermore, delete the following line from the Pageflow initializer:
> 
>     ActiveAdmin.application.load_paths.unshift(Dir[Pageflow::Engine.root.join('admins')])
> Instead insert the following line at the top of the Active Admin initializer:
> 
>     ActiveAdmin.application.load_paths.unshift(Pageflow.active_admin_load_path)
> See the Active Admin changelog for instructions on how to upgrade the Active Admin initializer. (#500)

**Comment by jtebbenGS** [comment]
This with a few more Gemfil deletions (i had 'state_machine' as well.

Thanks for pointing me to where I should have look all along. Got some ActiveAdmin stuff to work through, but doesn't appear major.
thanks again
