### ISSUE TITLE
Video Encoding is stucked at 100%

### ISSUE THREAD

**Issue by ablotny** [codevise/pageflow#69]
Hi,

I have a test installation of pageflow.
Everything seems to work except the encoding of a video.
As it can be seen in the picture the encoding is stucked at 100%:

![image](https://cloud.githubusercontent.com/assets/5426875/3688944/6667b098-133b-11e4-833c-5be7d7af3765.png)

I can see the encoded files stored at Amazon S3. Also the Zencoder API is called 7 times with 200 and 201 as returned status codes.
Zencoder is in trial mode which means that there are only 5 seconds videos created. Could that be an issue?

As I cannot see any failures in the log messages, can somebody give me a hint where to look for the problem?

Thanks and Greetings,
Alex

**Comment by CleverMobile2811** [comment]
Video/Audio stuck in 0% Encoding in progress.
I can see the encoding finished in Zencoder and also get the video from out-bucket in AWS3 encoded by Zencoder.
But still 0% Encoding in progress, As a result, can't publish the story.

**Comment by CleverMobile2811** [comment]
![untitled](https://user-images.githubusercontent.com/24418066/37574000-d438d132-2af3-11e8-850a-39a1fdf079d1.png)
