### ISSUE TITLE
Entry title must be validated for empty string

### ISSUE THREAD

**Issue by jrunkel** [codevise/pageflow#691]
It is currently possible to set the entry title to an empty string. On multiple pages within the active admin the title is used as link to the entry. Without a title it is therefore impossible to navigate to the entry.

**Comment by tf** [comment]
[Fixed upstream](https://github.com/codevise/pageflow/commit/f387ce4c96befe651de6bc3dfcc33e49c3f15203#diff-efe42a34ac82da0c9168513445117c28R36).

**Comment by jrunkel** [comment]
You might consider having a migration for that, too.
