### ISSUE TITLE
4k video gives Zencoder encoding error

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#730]
When uploading 4k video (4096x2160) ZenCoder fails:

> A resolution was not specified and the input resolution is greater than HD. Your account is not enabled for 4k transcoding. Please choose a resolution less than 2048x1080. You may also enable 4k transcoding by opting in here or by contacting saleseng@brightcove.com. Get more information in the documentation.

It only fails on output 11; all the others work.

**Comment by tf** [comment]
Could you paste the JSON representation (available via the Zencoder API request builder) of the Zencoder job into a gist?

**Comment by tilsammans** [comment]
https://gist.github.com/tilsammans/1eab2bd101ad1486c3e0707722cce464

**Comment by tf** [comment]
Hm. I have never seen this error before. It would be interesting to see the JSON of the job definition itself that can be displayed via `https://app.zencoder.com/request_builder?job=<job_id>`.

**Comment by tilsammans** [comment]
I think that's this: https://gist.github.com/tilsammans/309eeb4c119866fec722a021a7b82fb2

**Comment by tf** [comment]
Looks pretty normal to me. One thing I notice: I do not find an `outputs` item in the job definition corresponding to the failed item in the responds JSON. On the other hand, it says `"thumbnails": []` in the result, even though a thumbnail output was part of the job definition. I'd suggest you contact Zencoder support. Maybe they can say more.

**Comment by tilsammans** [comment]
Okay; done. Isn't it enough to ask them to enable 4k support?

**Comment by tf** [comment]
Maybe. I did not know though this was something to ask for.

**Comment by tilsammans** [comment]
Indeed, once I enabled 4k inputs at Zencoder (billed at 4x) the job went through.

**Comment by tf** [comment]
Would you mind adding an entry to the [troubleshooting wiki page](https://github.com/codevise/pageflow/wiki/Troubleshooting)? This seems like something others might encounter as well.

**Comment by tilsammans** [comment]
Done.
