### ISSUE TITLE
File processing only works when resque worker runs as root

### ISSUE THREAD

**Issue by rmoestl** [codevise/pageflow#732]
Hi!

First of all, thanks for open sourcing Pageflow.

I'm in charge of setting up Pageflow for a university and so far I've managed to have it up and running.

The only problem that I have and with which I struggle currently is, that **file processing** (image and video, haven't tried audio so far) hangs** when I run the **resque worker** as a **non-root user**.

When I run the resque worker as root, image and video processing works fine, loading things up to S3, encoding things in Zencoder etc.

It seems that it's a permissions problem. So I fiddled around with permission in `tmp/attachements`, even gave it 777. However, it had no positive effect. When resque worker runs as a non-root user, file processing hangs (i.e. after the "Successfully uploaded" step the UI hangs at "Processing.". In the case of image processing there does not appear any log messages in `jobs/production/resizing.log`. When running resque worker as root, log messages appear in the resizing.log. The imagemagick `convert` command is also available for the non-root user in use. Email invitations (that are obviously sent asynchronously in the resque worker) for new users are also working when ran as non-root.

Are there any other directories the file processing jobs use and which would prevent processing if permissions are not setup correctly?

Cheers,
Robert

**Comment by tf** [comment]
Hi!

Try installing [the resque web interface](https://github.com/resque/resque#rails-3) in your application. Then you can check if the jobs are enqueued correctly or if there are any failed jobs. Have you checked that the Redis server is accessible for non-root users? Which user user is the Rails app running as?

Cheers 
Tim

**Comment by rmoestl** [comment]
Hey, thanks for your quick reply @tf.

Just found the problem. Since I ran the resque worker task as root, the log files in `log/jobs/production` were owned by root. Then, when restarting resque worker task with a non-root user, the task was not allowed to replace the respective job log files (e.g. resizing.log) since they were owned by root.

Solution was to purge all log files in there and starting from a clean slate with the the non-root user :-)

Thanks again for you quick reply and for you guys open-sourcing it.

All the best,
Robert

**Comment by tf** [comment]
You're welcome!

Robert Möstl <notifications@github.com> schrieb am Do., 16. März 2017,
18:21:
