### ISSUE TITLE
RuntimeError at pageflow:install

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#754]
Hello there,

ive currently got a problem installing PageFlow on a Ubuntu 16.04 machine.
I previously installed it on my MacBook where everything went well.
On the Ubuntu machine i installed Ruby 2.3.1p112, Rails 4.2.7.1 and created a new Rails app.
As i try running:
`bundle exec rails generate pageflow:install`
i get a RuntimeError Pageflow has not been configured yet.
Someone ran into this problem before? As my ruby knowhow is close to 0 i really need help on this one.

Best regards,
Ronald

here is the whole error message:
![rails_generate_pageflow](https://cloud.githubusercontent.com/assets/15860150/25943348/dddaad0e-363f-11e7-9d99-59a7f50d72d1.png)

**Comment by tf** [comment]
This error often comes up when trying to run the generator in a Rails app where it has been run unsuccessfully before. Then the app can get into an invalid state. Does this happen on a newly generated Rails app?

**Comment by nerdusMaximus** [comment]
Yes this app was newly generated. But with the same name as a previous one. Maybe i should try to name it different? Or is there a way to clear the state of the app?

**Comment by tf** [comment]
Could not reproduce. Here's exactly what I did:

```
$ ruby -v 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
$ rvm gemset create dummy
$ rvm gemset use dummy
$ gem install rails -v 4.2.7.1
$ rails new pageflow_daad --database=mysql
$ cd pageflow_daad
$ vim config/database.yml 
# => valid credentials

$ bundle exec rake db:create
$ vim Gemfile
# => Insert 
gem 'pageflow', '0.11.3'
gem 'state_machine', git: 'https://github.com/codevise/state_machine.git'
$ bundle exec rails g pageflow:install
# => Generator runs successfully
```
Not sure what might be different about your setup.

**Comment by tf** [comment]
Maybe try running `bin/spring status` and `bin/spring stop` if it is running. There still might be old processes in the background.

**Comment by nerdusMaximus** [comment]
That is quite frustrating. 
I installed ruby via rbenv. Thats the first difference. I didnt execute the rake db:create before the generator. But that shouldnt be a critical point i guess.

Ill give it another shot exactly how you did it.

**Comment by tf** [comment]
rbenv should not make a difference IMO. I only used gemsets to ensure I actually use the exact same Rails version you do.

**Comment by nerdusMaximus** [comment]
is the step
`$ bundle exec rake db:create`
mandatory for the workflow to work properly?

**Comment by tf** [comment]
I guess, but it should not cause the error. 

I looked at your stacktrace again. And it looks like you might be be running in `production` environment. Maybe `RAILS_ENV` is set? At least I see from your stacktrace that eager loading is triggered, which only causes components of Pageflow to be loaded which depend on the configuration that is simply not there yet.

**Comment by nerdusMaximus** [comment]
YES! This helped!
Thank you a lot. 
I did set this variable a time ago in another try. Now the generator ran successfully.
Ill let you now if the rest of the installation runs smoove. Thank you a LOT!

**Comment by tf** [comment]
Great! Happy to help :smiley:
