### ISSUE TITLE
Image Upload stuck at "Processing."

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#759]
Hello again,

i now got my pageflow application running with nginx and passenger.
But somehow the image upload is a bit tricky.
I added `gem 'resque-scheduler', '~> 2.5.5'` to my Gemfile,
and `require 'resque_scheduler'` to the config.ru

Then i additionally startet 
`$ QUEUE=* rake resque:work RAILS_ENV=production`
and
`$ QUEUE=* rake resque:scheduler RAILS_ENV=production`
both in an own terminal window. I was able to upload one image to my first page of the example-entry. As i wanted to load an image for the second page its stuck at "Processing."

What exactly am i doing wrong or is it misconfigured?
I hope i can get some help on this one.

Best regards,
Ronald

**Comment by tf** [comment]
Have you already tried everything in [Troubleshooting](https://github.com/codevise/pageflow/wiki/Troubleshooting#image-and-media-processing)?

**Comment by nerdusMaximus** [comment]
Hello again :)

Redis server is running. I get no error `Error connecting to Redis on localhost:6379`.
All stated log files are free from error messages.

I do not get any error messages in the Pageflow Editor. It is just stuck in that state.

**Comment by nerdusMaximus** [comment]
I guess imagemagick was not installed. Then i still wonder why uploading one image was no problem.
Now installing imagemagick, two uploads where no problem.
Is there a way in which i dont have to run the resque:scheduler and resque:work in a single terminal?
As this jobs will expire as soon as i close the terminal/ssh connection or am i mistaking?

Best regards,
Ronald

**Comment by tf** [comment]
From the README:

> ## Running Pageflow
> 
> In addition to the Rails server, you need to start two Rake tasks for the background job processing. These tasks are listed in Procfile which is generated in the project root folder by the Pageflow installer.
> 
> Consider using the [foreman gem](https://github.com/ddollar/foreman) to start all of these processes (including the Rails server) with a single command in your development environment.

**Comment by nerdusMaximus** [comment]
Thanks for that quick answer, but does this work with the nginx+passenger constellation?

**Comment by tf** [comment]
Yes, why not. It's just a way to start multiple processes in development. Just don't include any Rails server since that is handled by passenger.

For production you want to look for something more stable, like [monit](https://mmonit.com/monit/). But that depends on you deployment choices.

**Comment by nerdusMaximus** [comment]
Ok thank you. This should be a production environment so i will checkout monit. Hope it is not too complicated as im in time pressure by now.

It seems as the naming of the files is a problem.
"kafka2.jpg" is not uploading successfully. It is stuck at "processing"
"kafkaagain.jpg" no problem. Gets uploaded just fine.

**Comment by tf** [comment]
Well, what's inside the log files which are mentioned in the trouble shooting guide?

**Comment by nerdusMaximus** [comment]
No errors at all:
`I, [2017-05-12T12:35:57.362639 #32107]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 4
I, [2017-05-12T12:36:02.234650 #32107]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 4
I, [2017-05-12T13:40:46.356765 #3749]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 7
I, [2017-05-12T13:40:52.346399 #3749]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 7
I, [2017-05-12T13:41:24.109508 #3889]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 8
I, [2017-05-12T13:41:29.567247 #3889]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 8
I, [2017-05-12T13:51:04.730827 #4307]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 10
I, [2017-05-12T13:51:07.921901 #4307]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 10
I, [2017-05-12T13:52:32.571503 #4477]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 13
I, [2017-05-12T13:52:35.779407 #4477]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 13
I, [2017-05-12T14:10:14.674449 #5171]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 16
I, [2017-05-12T14:10:20.840558 #5171]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 16
I, [2017-05-12T14:10:35.877999 #5299]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 17
I, [2017-05-12T14:10:40.940276 #5299]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 17
I, [2017-05-12T14:10:55.979674 #5425]  INFO -- : Pageflow::ProcessImageFileJob - perform for Pageflow::ImageFile 18
I, [2017-05-12T14:11:00.466529 #5425]  INFO -- : Pageflow::ProcessImageFileJob - result ok for Pageflow::ImageFile 18`

**Comment by tf** [comment]
And if you watch this file, is there a job for each and every file you upload? If for some files the upload requests succeeds, but no job processing takes place, you may have some stale resque workers living on your system which pick up jobs and die. Maybe do a `ps aux | grep resque` to see there are only the worker processes you expect.

**Comment by nerdusMaximus** [comment]
ok, there seems to be a bit more than expected:
![bildschirmfoto 2017-05-12 um 14 23 26](https://cloud.githubusercontent.com/assets/15860150/25997888/a8e74ad2-371e-11e7-85b6-46cdef9b65b3.png)

**Comment by nerdusMaximus** [comment]
So cleaning the running processes seems to clear all problems.
Thank you for the good support again 👍
