### ISSUE TITLE
Upload failure

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#761]
Hello again,

ive got my pageflow application now ready and running.
Still some flaws ill have to figure out with the help of the logfiles.
One issue i cant figure out myself. If i try to upload an image file of 3.7MB
the upload fails with a "Upload failure.".
This failure is not logged in any way. Neither in the /log/production.log nor in the /log/jobs/production/resizing.log
No output there at all.
Can someone give me a hint on this?

Thank you in advance and best regards,
Ronald

**Comment by tf** [comment]
Check your Nginx logs. Probably [client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) is not configured correctly. Non of this is really a Pageflow issue, though, but general topics on how to run Rails applications in production.

**Comment by nerdusMaximus** [comment]
Of course its the only part i didnt check. Thank you for that hint.
The Issue can be closed now.

Best regards,
Ronald
