### ISSUE TITLE
Invitation mail to User

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#762]
Hello again,

I hope this is my last time bothering you guys.
My current Problem is the following:
I try to create a new user but the Invitation is not sent:
If i check the /log/production.rb i find this:
![bildschirmfoto 2017-05-17 um 09 20 33](https://cloud.githubusercontent.com/assets/15860150/26142736/2afa714a-3ae2-11e7-9636-42697bdcfb12.png)
before this error i see the created mail inside the logs and there is one hint i find:

From: change-me-at-config-initializers-pageflow@example.com

This is the sender address as you can see. But at initializers/pageflow.rb i changed that line as follows:
`Pageflow.configure do |config|
  config.mailer_sender = 'pageflow@daad.com'`

Inside my /config/environments/production.rb i added this block which i found on stackoverflow.  No change in the error message:
`config.action_mailer.delivery_method = :sendmail
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default_options = {from: 'no-reply@daad.com'}
  config.action_mailer.default_url_options = {host: 'pageflow.daad.com'}`

I hope you can help me again as you did so well before.

Thank you in advance and best regards,
Ronald

**Comment by tf** [comment]
Have you restarted the Resque workers? In the default Pageflow setup, mails are sent in background jobs. Configuration (i.e. `config.mailer_sender` or anything in `config/environments/production.rb`) will only be read once during worker startup.

I have no experience with using Sendmail in a Rails setup. So I can only advise to refer to [the Action Mailer Rails guide](http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration) or look for answers on StackOverflow.

**Comment by nerdusMaximus** [comment]
Restarting the workers indeed did the trick. Thank you!
But now the next problem occurs:
i get 404 errors for images not found:

GET http://com-example-pageflow-out.s3-website-eu-west-1.amazonaws.com/bandwidth_probe_small.png?1495014184536 404 (Not Found)

This bucket is not in my pageflow.rb anymore. 
ive got this in my pageflow.rb
config.paperclip_s3_default_options.merge!(
    :s3_credentials => {
      :bucket => ENV.fetch('S3_BUCKET'),
      :access_key_id => ENV.fetch('S3_ACCESS_KEY'),
      :secret_access_key => ENV.fetch('S3_SECRET_KEY'),
      :s3_host_name => ENV.fetch('S3_HOST_NAME')
    },
    :s3_host_alias => ENV.fetch('S3_HOST_ALIAS'),
    :s3_protocol => ENV.fetch('S3_PROTOCOL')
  )

and all my ENV variables are set properly.
Why does the app bother with this buckets and with this images?

**Comment by tf** [comment]
Make sure that the bucket [contains the bandwidth probe images](https://github.com/codevise/pageflow/wiki/Setting-up-External-Services#bandwidth-detection). But here the the issue is something else: The URL is written from your env variables to Javascript during asset precompilation. If you change the `paperclip_default_options` you need to recompile your assets for changes to take effect.

**Comment by nerdusMaximus** [comment]
yes thats it. Recompiling the assets did it. Thanks for all your support. There are really a lot of steps to have in mind which are also not all that well documented to be honest.

Thank you a lot.

**Comment by tf** [comment]
We are happy to accept pull requests that fill gaps in the documentation. You can also contribute to the relevant wiki pages. I tried to add items for all issues you encountered to the [Troubleshooting guide](https://github.com/codevise/pageflow/wiki/Troubleshooting).  

Still, a lot of these topics are really specific to individual deployment choices or more general Rails deployment questions. As a Rails engine, Pageflow leaves a lot of choices for the developer of the actual Rails application. A complete guide on how to run Rails applications in production is beyond the scope of Pageflow's documentation
