### ISSUE TITLE
Client-side bandwidth and latency test

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#789]
Could we switch to https://github.com/beradrian/jsbandwidth to detect the bandwidth? It would simplify the setup a little and save on server bandwidth charges too.

**Comment by tf** [comment]
Didn't know that one. Given our move towards adaptive video streaming, starting with Pageflow 12, the result of the bandwidth detection will only be used for videos that do not have a DASH variant. So if we make changes to this area, it might be worth to look for ways to skip bandwidth detection altogether if all videos inside the entry do have adaptive streaming variants. That would be a nice way to gain some startup speed.

**Comment by tf** [comment]
Tempted to close this. Would prefer thinking about a way to skip bandwidth detection completely in cases where we are confident that the browser will pick HLS or DASH anyway.

**Comment by tilsammans** [comment]
If that's your intuition I'm happy to go with that!
