### ISSUE TITLE
Checklist for using Passenger and Apache2

### ISSUE THREAD

**Issue by fbuetefuer** [codevise/pageflow#812]
Hello,
can someone give me a step by step description for using Passenger with Apache2 to serve a pageflow website. Or tell me where I can find such an instruction.
Thank you

**Comment by tf** [comment]
Hi, 

Pageflow itself is not a Rails application, but a so called Rails engine that can be used inside a Rails application. There are many options regarding Rails application deployment. Still, most of these considerations are not Pageflow specific, so most Passenger tutorials should be be applicable to your case. Nevertheless the topic is somewhat out of scope for Pageflow's documentation. Therefore I am going to close this issue.
