### ISSUE TITLE
logs an documentation

### ISSUE THREAD

**Issue by brunojennrich** [codevise/pageflow#824]
hi there,

where can i get detailed loging about what goes wrong in pageflow.

the configuration ist so awfully described. i managed to get S3 pic upload done. but video upload does not work. and if zencoder is working? i dont know.

log/development.rb just tells me something about locks. but nothing else.

regards

bruno

**Comment by tf** [comment]
Have you checked the [Troubleshooting wiki page](https://github.com/codevise/pageflow/wiki/Troubleshooting)? PRs or wiki contributions to improve the documentation are always welcome.

**Comment by brunojennrich** [comment]
yes, i have read it. and there is not hint on regarding error messages concerning s3 upload, oder zencoder encoding

and as i saif, the logfiles don't giv any clue

**Comment by tf** [comment]
Then you need to describe your problem more closely.

**Comment by brunojennrich** [comment]
i upload a video

it is succesfully uploaded "Successfully uploaded."

i get a blinking/wating icon "Transfering to S3."

i need: a log file where i can see:

where the error occurs, to look for myself why the error occurs

images are transferred to S3 and are used from there.
video not
audio? i dont know. haven't tried yet

**Comment by tf** [comment]
What do you see in the log file `log/jobs/development/slow.log`? Are you running your app in development environment? You can look for entries in `log/development.log` starting with the `[paperclip]` tag. What do those say? Is there standard output in the console where you are running the Resque workers?

**Comment by brunojennrich** [comment]
i don't have a log/jobs/development/slow.log 

and i am expecting, that dev an prod behave the same. on with logs and checks an balances, the other without

**Comment by brunojennrich** [comment]
log/jobs/production is empty

**Comment by tf** [comment]
But you do have a Resque worker process running?

**Comment by brunojennrich** [comment]
the resque worker died... didn't see that, but now the encoding halts. 
and i need to know, wich errors occur.

s3 permissions, or wrong zencode keys, or whatever. where can i see that?

**Comment by tf** [comment]
Troubleshooting wiki page:

> #### Error Message in Pageflow Editor during Video Processing Step
> 
> Check `log/jobs/development/default.log` and `log/jobs/development/resize.log` to see why the job failed.

**Comment by brunojennrich** [comment]
Pageflow::UploadFileToS3Job - result ok for Pageflow::VideoFile 2
Pageflow::SubmitFileToZencoderJob - result ok for Pageflow::VideoFile 2

(same for videofile 1)

and waiting... forever

**Comment by tf** [comment]
do you see the job in the Zencoder web interface?

**Comment by brunojennrich** [comment]
yes... and i ve seen that there is something going terribly wrong....

**Comment by tf** [comment]
Please be more specific. I am trying to help you...

**Comment by tf** [comment]
Also do you see any logs for `PollZencoder` jobs in `resize.log`? Is the Resque scheuler running?

**Comment by brunojennrich** [comment]
yes. but now zencoder sais: everythings encoded, the files ecoded files are sent to my *-out bucket, but pageflow still waits for the end of encoding

**Comment by tf** [comment]
See my last post

**Comment by brunojennrich** [comment]
aahh.. cool... now i have to figure out, how to start 

QUEUE=* rake resque:work
and
rake resque:schedulerork

always and as background tasks/demons...

thanks!

**Comment by tf** [comment]
Consider using the generated `Procfile` to start all processes together using Foreman (see section in [README](https://github.com/codevise/pageflow#running-pageflow))
