### ISSUE TITLE
custom theme

### ISSUE THREAD

**Issue by brunojennrich** [codevise/pageflow#828]
i followed the steps to create a custom theme

`rails generate pageflow:theme my_custom_theme
`
and put

`# config.themes.register(:default)
  config.themes.register(:my_custom_theme)
` 

into 

`config/initializers/pageflow.rb`

and changed

`~/my_pageflow/app/assets/stylesheets/pageflow/themes/my_custom_theme/variables.scss`

to 

 $theme-name: "my_custom_theme";

 $main-color: #e74e25 !default;
 $main-color-dark: #c72e05 !default;
 $loading-spinner-background-color: #e74e25 !default;

goal:

change the color of the startting page (loading spinner?) to orange.

that didnt work.

i restartet the server

that didnt work.

how do i implement an own theme?

where do i find the meaning of the different variables (ive seen the document, where all possible variables are listed. but this is useless, because nowhere is stated, what each variable means, and the names are far from self explanatory).

the work with pageflow is an extremely frustrating endeavour. 

and when i say extremely i was overly polite.

**Comment by tf** [comment]
Well. Nobody forces you to use it. Let me just say that your overall tone in the conversation so far has been more then frustrating as well - and this is also being overly polite.

Feel free to come back, once you are ready to have a constructive conversation.

**Comment by brunojennrich** [comment]
well... we'll see...
