### ISSUE TITLE
Video Encoding failed with invalid api_key

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#844]
Hello pageflow Team,

a while ago i started using pageflow.
No i wanted to integrate videos on my site and added the zencoder configuration including the zencoder-api key inside my config/initializers/pageflow.rb
but when it comes to encoding i get an error saying "invalid api_key".
Im pretty sure that this is the right api key and i dont get any other information about which api key is used so maybe my key is not read at all by the application.

I have tried to `rake assets:precompile` but there for some reason an error occurs.
it says the following:
```
rake assets:precompile
Could not find json-1.8.6 in any of the sources
Run `bundle install` to install missing gems
```
and following this leads to another bunch of errors. Im quite frustrated again.
Is there any fast way to load the api_key into the application? Do i have to reload anything?

I hope you can help me with this one.
Thanks in advance and best regards
Ronald

**Comment by tf** [comment]
Hi Ronald,

Have you restarted the Resque workers after changing the settings? And also made sure there are no old worker processes still living in the background? That's a common case, where old resque worker processes still using the old config pick up jobs and fail.

Asset precompilation is not related to this topic. Depending on how you installed your gems, it might help to prefix the command the command with `bundle exec` to make it succeed. Still this has nothing to do with video encoding.

Tim

**Comment by nerdusMaximus** [comment]
Hello Tim, 
Thank you for your help.
I wanted to restart the worker, but at this call
```
rake resque:work QUEUE=* RAILS_ENV=production > /home/pageflow/pageflow_application/log/resquework.log &
```
i get this error:
```
rake aborted!
Bundler::GemNotFound: Could not find json-1.8.6 in any of the sources
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
/home/pageflow/pageflow_daad/config/boot.rb:3:in `<top (required)>'
/home/pageflow/pageflow_daad/config/application.rb:1:in `<top (required)>'
/home/pageflow/pageflow_daad/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/pageflow/pageflow_daad/config/boot.rb:3:in `<top (required)>'
/home/pageflow/pageflow_daad/config/application.rb:1:in `<top (required)>'
/home/pageflow/pageflow_daad/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
```
Im quite stuck.
I installed this whole thing in may and left in untouched since then. Now im comming back and suddenly nothing seems to work ^^

Thank you for your help and best regards,
Ronald

**Comment by tf** [comment]
Try running the command with `bundle exec`:

```
bundle exec rake resque:work QUEUE=* RAILS_ENV=production
```
Depending on how you installed your gems (e.g. if you did `bundle install --path vendor/bundle` or `bundle install --deployment`), just running `rake` uses the executable from your system ruby gems. But please also check via `ps aux|grep resque` that there are no other old resque worker processes running. Otherwise your new worker process might not get all of the jobs.

**Comment by nerdusMaximus** [comment]
Hello Tim,

after running your command it still tells me
```
Could not find json-1.8.6 in any of the sources
Run `bundle install` to install missing gems.
```
And i previously did shut down the old worker. Thats why its now that urgent that the new worker starts.

And thanks a lot for your support. I really appreciate it.

**Comment by tf** [comment]
How did you install the gems originally? Is there a '.bundle/config' file in your project root? If yes, paste it here. We might be able to tell how you installed the gems. Are their any (uncommitted?) Changes to the Gemfile or Gemfile.lock? What does running 'bundle install' say?

**Comment by tf** [comment]
I also see that you are using a system wide install of ruby. Is ruby installed from some package manager package (deb/rpm) that might have been upgraded during a dist update in the meantime? The fact that the Json gem no longer installs since header files are missing, makes me wonder whether something about the system changed since you last successfully installed gems.

**Comment by nerdusMaximus** [comment]
There is no '.bundle/config' in my project root.
Im pretty sure i just added some gems like described in "Gem Dependencies" here: https://github.com/codevise/pageflow#installation

here is my Gemfile and my Gemfile.lock
(i added .txt since i couldn't upload without)

[Gemfile.lock.txt](https://github.com/codevise/pageflow/files/1248237/Gemfile.lock.txt)
[Gemfile.txt](https://github.com/codevise/pageflow/files/1248238/Gemfile.txt)

Is there maybe a more direct way to communicate which would be more convenient for you and maybe quicker? I am endlessly thankfull

**Comment by nerdusMaximus** [comment]
Yes i have also notices that ruby was probably updated in the end of June. So thats about a month after i worked on this System. Could this be an issue?!

**Comment by tf** [comment]
Of course! Gems are installed for a specific version of Ruby. Change the Ruby version: all gems are gone.

**Comment by tf** [comment]
What does `bundle install` say? Will then probably fail with the same `json` gem error, though.

**Comment by nerdusMaximus** [comment]
sudo bundle install
```
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Using rake 12.0.0
Using i18n 0.8.1
Installing json 1.8.6 with native extensions
Using minitest 5.10.2
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using rack 1.6.6
Using mime-types-data 3.2016.0521
Using sass 3.4.23
Using thor 0.19.4
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using formtastic_i18n 0.6.0
Using arel 6.0.4
Using bundler 1.14.6
Using concurrent-ruby 1.0.5
Using tilt 2.0.7
Installing bcrypt 3.1.11 with native extensions
Installing debug_inspector 0.0.3 with native extensions
Installing byebug 9.0.6 with native extensions
Using cancancan 1.16.0
Using climate_control 0.1.0
Using orm_adapter 0.5.0
Using ejs 1.1.1
Using htmlentities 4.3.4
Using http_accept_language 2.1.0
Using multi_json 1.12.1
Using kramdown 1.13.2
Using mono_logger 1.1.0
Installing mysql2 0.4.6 with native extensions
Using pageflow-public-i18n 1.9.0
Using redis 3.0.7
Using state_machine 1.2.0 from https://github.com/codevise/state_machine.git (at master@f49c0bc)
Using videojs_rails 4.1.0
Installing yajl-ruby 1.3.0 with native extensions
Using rdoc 4.3.0
Using turbolinks-source 5.0.3
Using i18n-js 2.1.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/json-1.8.6/ext/json/ext/generator
/usr/bin/ruby2.3 -r ./siteconf20170824-30184-171xihd.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/json-1.8.6 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/json-1.8.6/gem_make.out

An error occurred while installing json (1.8.6), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.6'` succeeds before bundling.
```

**Comment by tf** [comment]
see https://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby

**Comment by nerdusMaximus** [comment]
so i should try
```
$ sudo apt-get install ruby-dev
```
?

**Comment by tf** [comment]
Yes.

**Comment by nerdusMaximus** [comment]
Oh my god!
THANK YOU!!!
it works and i could upload a video. Encoding did not get stuck.
Thank you so much.
Now i just need to start the worker in background so i can quit the connection to the server and its done.
You are my hero once again.
I think if i continue working with pageflow i should learn ruby and some other stuff.
Thanks again and best regards
Ronald

**Comment by tf** [comment]
:+1:
