### ISSUE TITLE
error updating pageflow

### ISSUE THREAD

**Issue by wdrhenus** [codevise/pageflow#852]
NameError: uninitialized constant Pageflow::BuiltInPageType
when we run: "bundle exec rake db:migrate"
[db-migrate-error.txt](https://github.com/codevise/pageflow/files/1270568/db-migrate-error.txt)

**Comment by tf** [comment]
You need to follow the upgrade steps in the changelog. For this particular case, see first item in [breaking changes section](https://github.com/codevise/pageflow/blob/12-0-stable/CHANGELOG.md#breaking-changes).

**Comment by wdrhenus** [comment]
Thank you first! - Sorry, but Changelog didn't help, we get the same Error-List

**Comment by tf** [comment]
Well, search for occurrences of `BuiltInPageType` in your app (most likely in `config/initializers/pageflow.rb`). If you replaced all occurrences (as described in the changelog), the error cannot happen anymore.
