### ISSUE TITLE
videos only run in Safari?

### ISSUE THREAD

**Issue by wdrhenus** [codevise/pageflow#854]
Sorry, I have one more question:
Pageflow installation 12.0.:
Pageflow works, but videos only run in Safari?
Thank you in advance for your support
W.-D.

**Comment by tf** [comment]
I'll need more info to be able to help. Any error messages in the dev tools console in the other browser (e.g. Chrome)?

**Comment by tilsammans** [comment]
We have seen this also @wdrhenus 

In our case, the CORS headers didn't come over from S3 to the CDN. So first thing is to check that the .mp4 file you're serving has the required CORS headers. They are mentioned in the setup steps on the Wiki.

**Comment by wdrhenus** [comment]
Thank you very much vor your ideas, but I can't solve it ...
https://pageflow.bildung.hessen.de/test-videos#42
Please take a look with Apple Safari and then with any other browser ...

**Comment by tf** [comment]
In the Chrome dev tools console it says:

![image](https://user-images.githubusercontent.com/26554/30149814-5eff2a9c-93a9-11e7-8dcb-a3bdbad3f62a.png)

Since you are using S3 static website to serve videos/images (which is far as I am aware does not support HTTPS), I suggest you switch your site to HTTP for now. Or at least first get it working over HTTP. Then HTTPS for published entries can be tackled in a separate step.

**Comment by wdrhenus** [comment]
Hallo, a'm sorry, the Handling with HTTPS and HTTP didn't help. I think, we have Problems with node/nodejs ...
I hope now, the new update will help. Is it able to install it in the same way like - "https://github.com/codevise/pageflow/wiki/Updating-Pageflow"?
Thank you!

**Comment by tf** [comment]
The "Updating Pageflow" still applies. I took another look at your example entry and in the browser console it still complains about missing `Access-Allow-Origin` headers when I access the HTTP variant. That's most likely the reason why videos are not working. So you have not updated your [CORS setup](https://github.com/codevise/pageflow/blob/12-0-stable/doc/setting_up_external_services.md#bucket-configuration), which is one of the bullet points in the [breaking changes section](https://github.com/codevise/pageflow/blob/12-0-stable/CHANGELOG.md#breaking-changes) of the Pageflow 12 changelog.

**Comment by wdrhenus** [comment]
Thank you very much Tim Fischbach,
I changed the CORS and everything moves...!!!

**Comment by tf** [comment]
You're welcome. :+1:
