### ISSUE TITLE
Resque Web

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#856]
What do you think about adding Resque Web to the install generator, @tf?

It's three very helpful lines:

``` ruby
  authenticate :user, lambda {|user| user.admin?} do
    mount Resque::Server.new, at: "/background_jobs"
  end
```

If you don't like it, I will add it to the Wiki.

**Comment by tf** [comment]
I like it. I did not know about the second parameter of `authenticate` to be honest. We use a slightly more cumbersome setup to integrate `Resque::Server` with our ability. But this is much more straight forward. 

This will also make "remote debugging" people's Resque issues much easier. :smile:
