### ISSUE TITLE
Web application could not be started after 'pageflow-external-links' installation

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#858]
Hello again.

I have just tried to install two Page Types which are

codevise/pageflow-external-links
&
codevise/pageflow-linkmap-page

After following the instruction and restarting the app via 
```
passenger-config restart-app
```
im left with the error "Web application could not be started" and the following error Code: 884c062c

It tells me to "bundle install" again since it seems that a gem is not found. 
The exception is saying that  pageflow-external-links-0.4.0 is not found. Here is the full exception:
```
-------- The exception is as follows: -------

Could not find pageflow-external-links-0.4.0 in any of the sources (Bundler::GemNotFound)
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /home/pageflow/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

maybe i should have restarted the app another way?
I hope you can help me as quick as you did previous times which i really appreciate.

Best regards,
Ronald

**Comment by tf** [comment]
Is the gem installed? Does `bundle list` inside the app directory include `pageflow-external-links`? If yes, what is the output of `bundle show pageflow-external-links`?

**Comment by nerdusMaximus** [comment]
`bundle list` lists the bundle:  * pageflow-external-links (0.4.0)
`bundle show pageflow-external-links` outputs this:
`/var/lib/gems/2.3.0/gems/pageflow-external-links-0.4.0`

**Comment by nerdusMaximus** [comment]
is there a way to tell Passenger which ruby gems to use? since every gem ist probably installed into /var/lib/gems. I just entered the gem into the Gemfile as stated in the tutorial.

**Comment by nerdusMaximus** [comment]
Or do i have to tell the application to install the gems into that rbenv ruby? Im confused...

**Comment by tf** [comment]
This depends on you Passenger setup. Please refer to the Passenger docs [1] [2]. I'm closing this issue since it is not about Pageflow but generally about how to run and deploy Rails applications.

[1] https://www.phusionpassenger.com/library/config/apache/reference/#passengerruby
[2] https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_ruby
