### ISSUE TITLE
Alternative Videos for mobile devices

### ISSUE THREAD

**Issue by nerdusMaximus** [codevise/pageflow#881]
Hey there,

is there a configuration which i am missing to serve different Videos (in size for slow connections) for a mobile connection? I wonder since this should show you different video possibilities in the editor which would be a nice feature.

Best regards,
Ronald

**Comment by tf** [comment]
Hi,

mobile devices use adaptive video streaming via HLS. When encoding, videos of different quality levels are created automatically. The HLS playlists offer those variants for the browser to choose from, based on connection speed. There is no way to manually specify a different video to use on mobile devices.

Best
Tim
