### ISSUE TITLE
Upload direct to S3

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#886]
I want to implement [direct file uploads to S3](https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails). This will improve uploading of large files.

I don't assume we can use Rails 5.2 in the very short term (it has ActiveStorage, which already has direct upload) so my time spent on this will be useful in the interim.

There are more things I would like to fix regarding file uploads, but doing them all at once is going to be a pain. For instance, I still want to clean up the paperclip initializer. Second, a shared volume for the local paperclip uploads is currently implied. But we use shared-nothing architecture and right now Pageflow doesn't handle that gracefully.

To go straight to the root problem of uploads I propose doing direct-to-S3 which solves the problem of local files altogether. What do you think? Any other areas I should take a look at first? We still are on aws gem version 1, we should start thinking about upgrading that too...

**Comment by tf** [comment]
Uploading directly to S3 would be really great. Without having given it much thought or knowing the technical details of direct S3 uploads, I'd imagine this to be quite an endeavor. From the top of my head, I can think of a whole list of things that would need to be changed:

* The (horrible horrible) `jquery-file-uploader`
* The controller end points that create new files
* The state machine and its Resque jobs that handle S3 upload and processing at the moment
* Paperclip integration

As a long term goal, using ActiveStorage would surely be the cleaner solution. But we'd need to upgrade to Rails 5 first and then find a way to migrate away from Paperclip, which also does not seem simple.

Can you outline how this change might look/what libraries would be used?

**Comment by tilsammans** [comment]
Without knowing too much about if you upload via ajax, and the drag-and-drop library you're using:

- [ ] make sure people create a new bucket for it
- [ ] make sure it has lifecycle rules: [sweep of failed uploads](https://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lc-expire-mpu) and remove objects after x days
- [ ] generate pre-signed POST on the server and set it as form action
- [ ] wait until successful upload and either use the hidden field or code in JavaScript
- [ ] make sure the usual Paperclip attachments are saved
- [ ] run background jobs as before

**Comment by tf** [comment]
Released in Pageflow 14.
