### ISSUE TITLE
Drop PhantomJS; use Chrome headless?

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#887]
I realise that the introduction of phantomjs to our test suite is relatively recent; but alas the project is not being maintained any more. Chrome headless works fine; [Rails switched too](https://github.com/rails/rails/pull/30930). We do the same?

**Comment by tf** [comment]
Sounds like a good idea!

**Comment by tilsammans** [comment]
This needs https://github.com/jejacks0n/teaspoon/pull/519 to be published first.
