### ISSUE TITLE
Reordering page in the editor does not refresh list

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#890]
Say I have a full story open in the editor, with lots of pages. With the arrow keys I can go down/up.

Now I reorder two pages via drag and drop. The arrow keys continue to reference the old pages. Meaning, they will skip around each other. When I refresh the browser, the behaviour changes. Now the arrow keys go through all pages sequentially.

I would expect the sequence to be updated right after the pages are swapped. I could swear it was this way in 0.11 too.

**Comment by tf** [comment]
This is definitely a bug. Does it only happen with keyboard navigation (vs e.g. mouse wheel)?

**Comment by tilsammans** [comment]
@martijnvantol can you elaborate?

**Comment by martijnvantol** [comment]
it also happens using the mousewheel and track pad. Tested in chrome and safari on macbook pro

**Comment by tf** [comment]
Confirmed. Starting with 12.0 we only [render](https://github.com/codevise/pageflow/blob/b2c5e5316a8d93eddf88db103b24af332d155bec/app/assets/javascripts/pageflow/editor/views/entry_preview_view.js#L12) a subset collection of [persisted pages](https://github.com/codevise/pageflow/blob/b2c5e5316a8d93eddf88db103b24af332d155bec/app/assets/javascripts/pageflow/editor/collections/pages_collection.js#L34) in the editor. Rendered pages need to have an id to be able to look up page attributes in the Redux store. The `SubsetCollection` only [ensures sorting propagates up](https://github.com/codevise/pageflow/blob/b2c5e5316a8d93eddf88db103b24af332d155bec/app/assets/javascripts/pageflow/editor/collections/subset_collection.js#L44) to the parent collection. Sorting the parent collection (i.e. moving pages in the sidebar) does not propagate down to the subset collection. I'll make a PR once I've tested the fix.
