### ISSUE TITLE
Reduce chance for console errors in theme selection dialog

### ISSUE THREAD

**Issue by tilsammans** [codevise/pageflow#907]
The new functionality to select a theme per entry is great. But the modal dialog where this happens can raise a lot of errors in the browser.

1. When a theme has no translation file, a visible error is shown on the screen.
1. When a theme has no preview image, a 404 is raised in the browser console, and infinitely loader animation is shown.

Both can be mitigated:

- [ ] default to the raw theme name when there is no theme name translation
- [ ] only show preview image when there is an actual `preview.png` available

**Comment by aviav** [comment]
I agree that the changes you describe would be improvements. Thanks for the report! Would you consider preparing a pull request?

**Comment by tilsammans** [comment]
Of course, however due to time pressure I won't be able to do this in the short term.

**Comment by aviav** [comment]
I considered preparing a pull request as well, but came to the same conclusion as you. Maybe it will happen when somebody works on themes the next time. Then it would be a small detour

**Comment by tf** [comment]
On the other hand one could also argue that these files and translations are simply required. The theme generator creates default preview images and the guide on creating themes list the needed translation keys.

**Comment by tf** [comment]
Coming back to this, I still think there are a lot of places where failing to provide the right translations causes visible error messages. I rather think of this as a feature, though. The i18n error messages as well as the 404 errors make it easy to see what exactly is missing.
