### ISSUE TITLE
Upgrade to Rails 5.2

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#939]
This issue tracks progress towards support for Rails 5.2. Changes will probably have to be applied in a series of PRs that we can link here.

#### Prerequisites

- Update `devise` to 4.4 (#932)

#### Steps

- [x] Ensure dummy app can be generated
- [x] Make specs pass (#938)
- [x] Release `13.0.beta1`
- [x] Upgrate all Pageflow plugins to work with this beta version (https://github.com/codevise/pageflow-external-links/pull/37, https://github.com/codevise/pageflow-linkmap-page/pull/35, https://github.com/codevise/pageflow-panorama/pull/22, https://github.com/codevise/pageflow-chart/pull/45)
- [x] Manual testing

**Comment by tilsammans** [comment]
Note that #932 will already use ActiveJob, specifically `.deliver_later`. When no queue adapter is set for legacy applications, ActiveJob will still function, and do the work synchronously. I find this acceptable given the low volume of these emails.

If you don't, we have to switch order of pull requests and re-generate `config/application.rb` first, to configure the queue adapter. I am leaving judgement to @tf

**Comment by tf** [comment]
Isn't this more related to #940 than to this issue?

**Comment by tilsammans** [comment]
You're right, I commented in the wrong pull request.
