### ISSUE TITLE
Background media playback on mobile browsers and Safari

### ISSUE THREAD

**Issue by tf** [codevise/pageflow#950]
Mobile browsers and current versions of Safari do not allow autoplaying video elements unless they are muted. Using WebAudio API, audio files can be autoplayed after a first user interaction has unlocked the audio context. 

Previous behavior on mobile browsers:

* We mute page background video loops to allow autoplay.
* Atmo is disabled since the current implementation uses one audio elements per audio file which would have to be unlocked by user interaction individually to be played.
* Autoplay of media on video and audio pages is disabled. User can start playback via play button.

Since Safari adopted autoplay restrictions on desktop, background video was basically broken. #949 does most of the work required to improve this situation:

* Replaces previous audio library with Howler, which supports playing all audios via a single audio context that can be unlocked by a single user interaction.
* Plays sound of muted background videos via this audio context once it is unlocked.
* No longer needs to disable atmo on mobile devices.
* Displays a button to unmute background media which provides the required user interaction.

Remaining open questions:

1. Should there be logic to only display the unmute button if the entry actually contains either background videos or pages with atmo audio? 

   Detecting pages like this might be tricky since (a) background videos might not have an audio track to begin with and (b) figuring out if a page has an atmo audio file requires actually looking up the file since audio file ids in the page configuration are allowed to point to files which have been removed from the entry. 

2. Should clicking the "Let's go" button inside the multimedia alert already unmute background media?

   There still might be value in letting the user view the entry with background media disabled. On the other hand, having to click an unmute button after just having been alerted that there will be sound might be confusing.

Remaining tasks:

- [ ] Use Howler to play atmo and background video sound (#949)
- [ ] Update help texts to remove hint about disabled atmo on mobile

**Comment by tf** [comment]
@tilsammans We are finally getting around to tackling this issue. Happy to hear your thoughts.

**Comment by danielmorlock** [comment]
It look's like the problem also occurs on Desktop Browsers:
![warning](https://user-images.githubusercontent.com/1263320/56150931-4f402f00-5fb0-11e9-87e5-56ef76c84e80.jpg)
Tested with Chromium 73.0.3683.75.

**Comment by tf** [comment]
@danielmorlock Far as I know, the console warning does not indicate a problem, but rather happens when we try to [resume the the audio context](https://github.com/codevise/pageflow/blob/396f1ad81aa4f55cdd1f276c9d4e2f1b5ea033d0/app/assets/javascripts/pageflow/media_player/volume_fading/web_audio.js#L24) since there is now way of knowing whether we come from a user gesture. The Hound approach described above and implemented in #949 still has synchronicity issues when playing uncached videos and is therefore blocked. The current state of autoplay support is outlined in [this doc file]( https://github.com/codevise/pageflow/blob/master/doc/media_autoplay_behavior.md).
