### ISSUE TITLE
Video/Audio 0% Encoding in progress

### ISSUE THREAD

**Issue by CleverMobile2811** [codevise/pageflow#963]
Image uploading and processing successfully.
Video/Audio uploading and encoded into output bucket successfully.
But still 0% Encoding in progress, so can't select any video/audio file and can't publish the story too.
Waiting for your reply.
Thank for your time.

**Comment by tf** [comment]
Have you checked the [Troubleshooting wiki page](https://github.com/codevise/pageflow/wiki/Troubleshooting)? Sounds like your resque scheduler might not be working. Do you have the Resque web interface installed? Do you see any failed or pending jobs there?
