### ISSUE TITLE
Resque worker skips resizing job

### ISSUE THREAD

**Issue by DeEgge** [codevise/pageflow#967]
I am currently trying out pageflow. Uploading images to S3 seems to work fine, but it stops at the 'Processing'-step.

The `resizing.log` reads the following:

```log
I, [2018-05-01T17:48:24.316050 #12535]  INFO -- : Pageflow::ProcessFileJob - perform for Pageflow::ImageFile 11
I, [2018-05-01T17:48:24.537290 #12535]  INFO -- : Pageflow::ProcessFileJob - Pageflow::ImageFile 11 not found. Skipping job.
```

I've gone through the Troubleshooting section, but with no luck. ImageMagick is installed. 

Any help would be much appreciated, thanks!

**Comment by tf** [comment]
This [log output occurs](https://github.com/codevise/state_machine_job/blob/c0086312d393681bf072a62db2fed433b90f4ded/lib/state_machine_job.rb#L31) when the record for the job cannot be found in the database. This can happen, for example, if the image has already been deleted again before the processing job ran. If it happens consistently, it can be a sign that the web server and the Resque workers are looking at different databases. The Resque workers could be running in a different Rails env for example (i.e. `development` vs `production`). Could this be the case here?

**Comment by DeEgge** [comment]
This indeed seemed to be the case. Now it says processing failure ;) but I'll figure that out myself. Thanks for your help, @tf
