### ISSUE TITLE
Not able to upload images/videos.

### ISSUE THREAD

**Issue by rmpanovka** [codevise/pageflow#990]
I've set up AWS and Zencoder, but looks like it is not working. When I try to upload images and videos, an exclamation icon pops up. 

Here's the config:

config.paperclip_s3_default_options.merge!(
    s3_credentials: {
      bucket: 'xxx',
      access_key_id: 'xxx',
      secret_access_key: 'xxx'
    },
    s3_host_name: 's3.us-east-1.amazonaws.com',
    s3_region: 'us-east-1',
    s3_host_alias: 'de-xxx-pageflow-development.s3-website-us-east-1.amazonaws.com',
    s3_protocol: 'http'
)

Can you help?

**Comment by tf** [comment]
Have you checked the [Troubleshooting wiki page](https://github.com/codevise/pageflow/wiki/Troubleshooting)?

**Comment by rmpanovka** [comment]
Hey 
Yes, I've looked in to the page but looks like I'm stuck. Here are the logs, I see the error. What am I missing?

`Rebeccas-MacBook-Pro:pretty_reports rebeccapanovka$ foreman start -f Procfile 
23:25:55 web.1       | started with pid 67778
23:25:55 worker.1    | started with pid 67779
23:25:55 scheduler.1 | started with pid 67780
23:25:59 scheduler.1 | resque-scheduler: [INFO] 2018-08-20T23:25:59-04:00: Loading Schedule
23:25:59 worker.1    | WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.
23:25:59 scheduler.1 | resque-scheduler: [INFO] 2018-08-20T23:25:59-04:00: Schedule empty! Set Resque.schedule
23:25:59 scheduler.1 | resque-scheduler: [INFO] 2018-08-20T23:25:59-04:00: Schedules Loaded
23:25:59 scheduler.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/rebeccapanovka/.rvm/gems/ruby-2.3.1/gems/resque-scheduler-2.5.5/lib/resque/scheduler_locking.rb:88:in `redis_master_version')
23:25:59 scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/rebeccapanovka/.rvm/gems/ruby-2.3.1/gems/resque-scheduler-2.5.5/lib/resque/scheduler/lock/resilient.rb:61:in `acquire_sha')
23:25:59 web.1       | [2018-08-20 23:25:59] INFO  WEBrick 1.3.1
23:25:59 web.1       | [2018-08-20 23:25:59] INFO  ruby 2.3.1 (2016-04-26) [x86_64-darwin17]
23:25:59 web.1       | [2018-08-20 23:25:59] INFO  WEBrick::HTTPServer#start: pid=67778 port=3000
23:26:04 scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/rebeccapanovka/.rvm/gems/ruby-2.3.1/gems/resque-scheduler-2.5.5/lib/resque/scheduler/lock/resilient.rb:38:in `locked_sha')

....

23:27:23 web.1       | Started POST "/editor/entries/6/files/image_files" for ::1 at 2018-08-20 23:27:23 -0400
23:27:23 web.1       | Processing by Pageflow::Editor::FilesController#create as JSON
23:27:23 web.1       |   Parameters: {"authenticity_token"=>"xxx", "image_file"=>{"rights"=>"", "configuration"=>{"alt"=>""}, "attachment"=>#<ActionDispatch::Http::UploadedFile:0x007ffdcf569f58 @tempfile=#<Tempfile:/var/folders/c3/1076040d68n_01_llxg6vbgw0000gn/T/RackMultipart20180820-67778-9ebps3.jpg>, @original_filename="94PccMFW_400x400.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"image_file[attachment]\"; filename=\"94PccMFW_400x400.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "entry_id"=>"6", "collection_name"=>"image_files"}
23:27:23 web.1       |   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
23:27:23 web.1       |   Pageflow::Entry Load (0.3ms)  SELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`slug` = '6' LIMIT 1
23:27:23 web.1       |   Pageflow::Entry Load (0.3ms)  SELECT  `pageflow_entries`.* FROM `pageflow_entries` WHERE `pageflow_entries`.`id` = 6 LIMIT 1
23:27:23 web.1       |   Pageflow::Revision Load (0.3ms)  SELECT  `pageflow_revisions`.* FROM `pageflow_revisions` WHERE `pageflow_revisions`.`entry_id` = 6 AND (frozen_at IS NULL) LIMIT 1
23:27:23 web.1       |   Pageflow::EditLock Load (0.4ms)  SELECT  `pageflow_edit_locks`.* FROM `pageflow_edit_locks` WHERE `pageflow_edit_locks`.`entry_id` = 6 LIMIT 1
23:27:23 web.1       |   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
23:27:23 web.1       |    (0.1ms)  BEGIN
23:27:23 web.1       |   SQL (0.3ms)  UPDATE `pageflow_edit_locks` SET `pageflow_edit_locks`.`updated_at` = '2018-08-21 03:27:23' WHERE `pageflow_edit_locks`.`id` = 1
23:27:23 web.1       |    (127.0ms)  COMMIT
23:27:23 web.1       | Unpermitted parameters: rights, configuration
23:27:23 web.1       | Unpermitted parameters: rights, configuration
23:27:23 web.1       | Unpermitted parameters: configuration, attachment
23:27:23 web.1       | Unpermitted parameters: rights, configuration, attachment
23:27:23 web.1       | Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/c3/1076040d68n_01_llxg6vbgw0000gn/T/9b0aa6fa92257652a74d71b0cab2d14c20180820-67778-1u1i6is.jpg[0]' 2>/dev/null
23:27:23 web.1       |    (0.3ms)  BEGIN
23:27:23 web.1       |    (0.2ms)  ROLLBACK
23:27:23 web.1       | Completed 500 Internal Server Error in 217ms (ActiveRecord: 129.8ms)
23:27:23 web.1       | 
23:27:23 web.1       | NoMethodError (protected method `around_validation' called for #<StateMachine::Machine:0x007ffdc463f960>
23:27:23 web.1       | Did you mean?  around_transition):
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:455:in `public_send'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:455:in `block in make_lambda'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:312:in `block in halting'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:497:in `block in around'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
23:27:23 web.1       |   activemodel (4.2.7.1) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
23:27:23 web.1       |   activemodel (4.2.7.1) lib/active_model/validations.rb:338:in `valid?'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/validations.rb:58:in `valid?'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/validations.rb:83:in `perform_validations'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/validations.rb:37:in `save'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/attribute_methods/dirty.rb:21:in `save'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
23:27:23 web.1       |   ar_after_transaction (0.4.2) lib/ar_after_transaction.rb:19:in `block in transaction_with_after'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:220:in `transaction'
23:27:23 web.1       |   ar_after_transaction (0.4.2) lib/ar_after_transaction.rb:17:in `transaction_with_after'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:286:in `block in save'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:285:in `save'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:483:in `block in save'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:502:in `block (2 levels) in around_save'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:150:in `block in run_actions'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:170:in `catch_exceptions'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:148:in `run_actions'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:133:in `run_callbacks'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:212:in `run_callbacks'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:63:in `block (2 levels) in perform'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:63:in `catch'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:63:in `block in perform'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:186:in `within_transaction'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/transition_collection.rb:62:in `perform'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:502:in `block in around_save'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:530:in `block in transaction'
23:27:23 web.1       |   ar_after_transaction (0.4.2) lib/ar_after_transaction.rb:19:in `block in transaction_with_after'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/transactions.rb:220:in `transaction'
23:27:23 web.1       |   ar_after_transaction (0.4.2) lib/ar_after_transaction.rb:17:in `transaction_with_after'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:529:in `transaction'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:501:in `around_save'
23:27:23 web.1       |   state_machine (1.2.0) lib/state_machine/integrations/active_record.rb:483:in `save'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/persistence.rb:34:in `create'
23:27:23 web.1       |   pageflow (12.1.0) app/models/pageflow/draft_entry.rb:39:in `create_file'
23:27:23 web.1       |   pageflow (12.1.0) app/controllers/pageflow/editor/files_controller.rb:22:in `create'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
23:27:23 web.1       |   actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/railtie.rb:194:in `public_send'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
23:27:23 web.1       |   http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
23:27:23 web.1       |   i18n-js (2.1.2) lib/i18n-js/middleware.rb:11:in `call'
23:27:23 web.1       |   warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
23:27:23 web.1       |   warden (1.2.7) lib/warden/manager.rb:35:in `catch'
23:27:23 web.1       |   warden (1.2.7) lib/warden/manager.rb:35:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/etag.rb:24:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/conditionalget.rb:38:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/head.rb:13:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/session/abstract/id.rb:225:in `context'
23:27:23 web.1       |   rack (1.6.10) lib/rack/session/abstract/id.rb:220:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
23:27:23 web.1       |   activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
23:27:23 web.1       |   web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
23:27:23 web.1       |   web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
23:27:23 web.1       |   web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/runtime.rb:18:in `call'
23:27:23 web.1       |   activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/lock.rb:17:in `call'
23:27:23 web.1       |   actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
23:27:23 web.1       |   railties (4.2.7.1) lib/rails/application.rb:165:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/lock.rb:17:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/content_length.rb:15:in `call'
23:27:23 web.1       |   rack (1.6.10) lib/rack/handler/webrick.rb:88:in `service'
23:27:23 web.1       |   /Users/rebeccapanovka/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
23:27:23 web.1       |   /Users/rebeccapanovka/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
23:27:23 web.1       |   /Users/rebeccapanovka/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
23:27:23 web.1       | 
23:27:23 web.1       | 
`

**Comment by tf** [comment]
Please post your Gemfile.

**Comment by rmpanovka** [comment]
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'pageflow', '~> 12.1.0'


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

**Comment by tf** [comment]
Though it's quite hard to read in your comment, I think, the entry for the `state_machine` gem is missing. Take another look at the install instructions in the Pageflow readme. You need to use the fork, since the latest released version is not compatible with Rails 4 and leads to the error you described.

**Comment by tf** [comment]
Also please note, that the README on `master` already targets the so far unreleased version 13 of Pageflow. You need to follow the instructions in the [README on the `12-x-stable` branch](https://github.com/codevise/pageflow/blob/12-x-stable/README.md).

To make my previos post more precise, the following line is missing from your `Gemfile`:

```
# Required for Rails 4.2 compatibility
gem 'state_machine', git: 'https://github.com/codevise/state_machine.git'
```
