### ISSUE TITLE
Autoscroll for pages

### ISSUE THREAD

**Issue by marcek** [codevise/pageflow#992]
Hi there,
is it possible to set an auto scroll for pageflow pages ? I mean scrolling to next screen after for example  10 seconds ? You provide going to a next page when video ends so why not for other type of pages ?

**Comment by tf** [comment]
Hi,
there is no such feature at the moment. For videos there is a well defined moment when the video ends and it is save to go to the next page. For all other pages, I see no way how to be sure the user has actually finished reading or looking at the content.

**Comment by marcek** [comment]
Ok, thank you for the answer
