### ISSUE TITLE
Setup for node

### ISSUE THREAD

**Issue by tim-wgbh** [codevise/pageflow#995]
Hello. I'm trying out pageflow for my organization and have run into the following problem

_Error: couldn't find file './dist/react' under ....rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bundler/gems/pageflow-03a991db7d47/app/assets/javascripts' with type 'application/javascript'_

Looks like node_package needs to be built. I tried rake pageflow:node_package:build - no help.

Configuration:
ruby 2.4.2
rails 4.2.8
pageflow 12.2.0

Others as in attached Gemfile
[Gemfile.txt](https://github.com/codevise/pageflow/files/2401926/Gemfile.txt)

I saw in an issue that Webpack is now being used to build JS assets. Is there documentation for that?

**Comment by tim-wgbh** [comment]
I'm not trying to develop, I'm just trying to run, following the getting-started documentation on github

**Comment by tf** [comment]
The error looks like you are trying to use Pageflow from a git source in your Gemfile: 

```
# DOES NOT WORK
gem 'pageflow', '~> 12.2.0', :git => 'https://github.com/codevise/pageflow.git', :branch => '12-2-stable`)
```

That is not supported at the moment. The most current stable version is 12.2. It's [up on Rubygems](https://rubygems.org/gems/pageflow/versions/12.2.0) and should work fine:

```
gem 'pageflow', '~> 12.2'
``` 

Maybe you did not bundle/restart the server after changing the Gemfile?

**Comment by tim-wgbh** [comment]
Got it working thanks. Iif you specify the gem version as indicated in the documentation  - X.Y.Z, bundler pulls in v. 0.10.0. You need to specify only the major and minor version.
gem 'pageflow', '~> 12.2'
